/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class ClaimsUWLinkedTask extends ClaimsUWLinkedTaskBase
{
    public ClaimsUWLinkedTask()
    {
        this((BusObjectConfig)null);
    }

    public ClaimsUWLinkedTask(BusObjectConfig config)
    {
        super(config);
    }

}
