/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class deleteCase extends deleteCaseBase
{
    public deleteCase()
    {
        this((BusObjectConfig)null);
    }

    public deleteCase(BusObjectConfig config)
    {
        super(config);
    }

}
