/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class ManualTaskDetails extends ManualTaskDetailsBase
{
    public ManualTaskDetails()
    {
        this((BusObjectConfig)null);
    }

    public ManualTaskDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static com.cica.uw.ManualTaskDetails GetManualTaskDetailsForTaskID(String TaskId)
    {
        String queryText = "SELECT * FROM ManualTaskDetails WHERE ProcessInstanceId='"+TaskId+"'";
        QueryObject query = new QueryObject(queryText);
       // query.addParameter("TaskId", "ManualTaskDetails.TaskId", QueryObject.PARAM_STRING, TaskId);//NOPMD
        query.setResultClass(ManualTaskDetails.class);
        return (ManualTaskDetails)query.getObject();
    }

    public static com.cica.uw.ManualTaskDetails GetTaskDetailsForPKId(String PKId)
    {
        String queryText = "SELECT * FROM ManualTaskDetails WHERE Id=:PKId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PKId", "ManualTaskDetails.Id", QueryObject.PARAM_STRING, PKId);//NOPMD
        query.setResultClass(ManualTaskDetails.class);
        return (ManualTaskDetails)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.ManualTaskDetails> getRecordsFromManualTaskDetailsForStatus(String Status)
    {
      String queryText = "select * from ManualTaskDetails where Status='"+Status+"'";
        QueryObject query = new QueryObject(queryText);
      //  query.addParameter("Status", "ManualTaskDetails.Status", QueryObject.String, String);//NOPMD
        query.setResultClass(ManualTaskDetails.class);
        return query.getObjects();
    }

}
