/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class PHSManualUWLinkedTaskBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_DestinationCaseModel = "DestinationCaseModel";
    public final static String ATTR_DestinationTaskName = "DestinationTaskName";
    public final static String ATTR_SourceCaseModel = "SourceCaseModel";
    public final static String ATTR_SourceTaskName = "SourceTaskName";
    public final static String ATTR_SourceTaskID = "SourceTaskID";
    public final static String ATTR_SourceTaskAssignee = "SourceTaskAssignee";
    public final static String ATTR_DestinationTaskID = "DestinationTaskID";
    public final static String ATTR_DestinationTaskCompletionStatus = "DestinationTaskCompletionStatus";
    public final static String ATTR_SourceResponseStatus = "SourceResponseStatus";
    public final static String ATTR_TaskName = "TaskName";
    public final static String ATTR_TaskId = "TaskId";
    public final static String ATTR_Customer = "Customer";
    public final static String ATTR_ClaimantName = "ClaimantName";
    public final static String ATTR_AgentCode = "AgentCode";
    public final static String ATTR_DocumentID = "DocumentID";
    public final static String ATTR_IndexClass = "IndexClass";
    public final static String ATTR_Notes = "Notes";
    public final static String ATTR_Status = "Status";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_ProcessedFlag = "ProcessedFlag";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(PHSManualUWLinkedTask.class);
            s_classInfo.setTableName("PHSManualUWLinkedTask");
            s_classInfo.setUIDElements(new String[]{ATTR_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DestinationCaseModel);
                ai.setJavaName(ATTR_DestinationCaseModel);
                ai.setColumnName(ATTR_DestinationCaseModel);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DestinationCaseModel);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DestinationTaskName);
                ai.setJavaName(ATTR_DestinationTaskName);
                ai.setColumnName(ATTR_DestinationTaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DestinationTaskName);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SourceCaseModel);
                ai.setJavaName(ATTR_SourceCaseModel);
                ai.setColumnName(ATTR_SourceCaseModel);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SourceCaseModel);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SourceTaskName);
                ai.setJavaName(ATTR_SourceTaskName);
                ai.setColumnName(ATTR_SourceTaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SourceTaskName);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SourceTaskID);
                ai.setJavaName(ATTR_SourceTaskID);
                ai.setColumnName(ATTR_SourceTaskID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SourceTaskID);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SourceTaskAssignee);
                ai.setJavaName(ATTR_SourceTaskAssignee);
                ai.setColumnName(ATTR_SourceTaskAssignee);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SourceTaskAssignee);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DestinationTaskID);
                ai.setJavaName(ATTR_DestinationTaskID);
                ai.setColumnName(ATTR_DestinationTaskID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DestinationTaskID);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DestinationTaskCompletionStatus);
                ai.setJavaName(ATTR_DestinationTaskCompletionStatus);
                ai.setColumnName(ATTR_DestinationTaskCompletionStatus);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DestinationTaskCompletionStatus);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SourceResponseStatus);
                ai.setJavaName(ATTR_SourceResponseStatus);
                ai.setColumnName(ATTR_SourceResponseStatus);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_SourceResponseStatus);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskName);
                ai.setJavaName(ATTR_TaskName);
                ai.setColumnName(ATTR_TaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskName);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskId);
                ai.setJavaName(ATTR_TaskId);
                ai.setColumnName(ATTR_TaskId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskId);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Customer);
                ai.setJavaName(ATTR_Customer);
                ai.setColumnName(ATTR_Customer);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Customer);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ClaimantName);
                ai.setJavaName(ATTR_ClaimantName);
                ai.setColumnName(ATTR_ClaimantName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ClaimantName);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AgentCode);
                ai.setJavaName(ATTR_AgentCode);
                ai.setColumnName(ATTR_AgentCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AgentCode);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DocumentID);
                ai.setJavaName(ATTR_DocumentID);
                ai.setColumnName(ATTR_DocumentID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DocumentID);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_IndexClass);
                ai.setJavaName(ATTR_IndexClass);
                ai.setColumnName(ATTR_IndexClass);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_IndexClass);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Notes);
                ai.setJavaName(ATTR_Notes);
                ai.setColumnName(ATTR_Notes);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Notes);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Status);
                ai.setJavaName(ATTR_Status);
                ai.setColumnName(ATTR_Status);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Status);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ProcessedFlag);
                ai.setJavaName(ATTR_ProcessedFlag);
                ai.setColumnName(ATTR_ProcessedFlag);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ProcessedFlag);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public PHSManualUWLinkedTaskBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getID()
    {
        return getLongProperty(ATTR_ID);
    }

    public void setID(long value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getDestinationCaseModel()
    {
        return getStringProperty(ATTR_DestinationCaseModel);
    }

    public void setDestinationCaseModel(String value)
    {
        setProperty(ATTR_DestinationCaseModel, value, 0);
    }

    public String getDestinationTaskName()
    {
        return getStringProperty(ATTR_DestinationTaskName);
    }

    public void setDestinationTaskName(String value)
    {
        setProperty(ATTR_DestinationTaskName, value, 0);
    }

    public String getSourceCaseModel()
    {
        return getStringProperty(ATTR_SourceCaseModel);
    }

    public void setSourceCaseModel(String value)
    {
        setProperty(ATTR_SourceCaseModel, value, 0);
    }

    public String getSourceTaskName()
    {
        return getStringProperty(ATTR_SourceTaskName);
    }

    public void setSourceTaskName(String value)
    {
        setProperty(ATTR_SourceTaskName, value, 0);
    }

    public String getSourceTaskID()
    {
        return getStringProperty(ATTR_SourceTaskID);
    }

    public void setSourceTaskID(String value)
    {
        setProperty(ATTR_SourceTaskID, value, 0);
    }

    public String getSourceTaskAssignee()
    {
        return getStringProperty(ATTR_SourceTaskAssignee);
    }

    public void setSourceTaskAssignee(String value)
    {
        setProperty(ATTR_SourceTaskAssignee, value, 0);
    }

    public String getDestinationTaskID()
    {
        return getStringProperty(ATTR_DestinationTaskID);
    }

    public void setDestinationTaskID(String value)
    {
        setProperty(ATTR_DestinationTaskID, value, 0);
    }

    public String getDestinationTaskCompletionStatus()
    {
        return getStringProperty(ATTR_DestinationTaskCompletionStatus);
    }

    public void setDestinationTaskCompletionStatus(String value)
    {
        setProperty(ATTR_DestinationTaskCompletionStatus, value, 0);
    }

    public String getSourceResponseStatus()
    {
        return getStringProperty(ATTR_SourceResponseStatus);
    }

    public void setSourceResponseStatus(String value)
    {
        setProperty(ATTR_SourceResponseStatus, value, 0);
    }

    public String getTaskName()
    {
        return getStringProperty(ATTR_TaskName);
    }

    public void setTaskName(String value)
    {
        setProperty(ATTR_TaskName, value, 0);
    }

    public String getTaskId()
    {
        return getStringProperty(ATTR_TaskId);
    }

    public void setTaskId(String value)
    {
        setProperty(ATTR_TaskId, value, 0);
    }

    public String getCustomer()
    {
        return getStringProperty(ATTR_Customer);
    }

    public void setCustomer(String value)
    {
        setProperty(ATTR_Customer, value, 0);
    }

    public String getClaimantName()
    {
        return getStringProperty(ATTR_ClaimantName);
    }

    public void setClaimantName(String value)
    {
        setProperty(ATTR_ClaimantName, value, 0);
    }

    public String getAgentCode()
    {
        return getStringProperty(ATTR_AgentCode);
    }

    public void setAgentCode(String value)
    {
        setProperty(ATTR_AgentCode, value, 0);
    }

    public String getDocumentID()
    {
        return getStringProperty(ATTR_DocumentID);
    }

    public void setDocumentID(String value)
    {
        setProperty(ATTR_DocumentID, value, 0);
    }

    public String getIndexClass()
    {
        return getStringProperty(ATTR_IndexClass);
    }

    public void setIndexClass(String value)
    {
        setProperty(ATTR_IndexClass, value, 0);
    }

    public String getNotes()
    {
        return getStringProperty(ATTR_Notes);
    }

    public void setNotes(String value)
    {
        setProperty(ATTR_Notes, value, 0);
    }

    public String getStatus()
    {
        return getStringProperty(ATTR_Status);
    }

    public void setStatus(String value)
    {
        setProperty(ATTR_Status, value, 0);
    }

    public java.sql.Date getCreatedDate()
    {
        return getSqlDateProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.sql.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getProcessedFlag()
    {
        return getStringProperty(ATTR_ProcessedFlag);
    }

    public void setProcessedFlag(String value)
    {
        setProperty(ATTR_ProcessedFlag, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.PHSManualUWLinkedTask> getNextPHSManualUWLinkedTaskObjects(long ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PHSManualUWLinkedTask\" where (\"ID\" > :ID) order by \"ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(ID));//NOPMD
        query.setResultClass(PHSManualUWLinkedTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.PHSManualUWLinkedTask getPHSManualUWLinkedTaskObject(long ID)
    {
        String queryText = "select * from \"PHSManualUWLinkedTask\" where \"ID\" = :ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(ID));//NOPMD
        query.setResultClass(PHSManualUWLinkedTask.class);
        return (PHSManualUWLinkedTask)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.PHSManualUWLinkedTask> getPHSManualUWLinkedTaskObjects(long fromID, long toID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PHSManualUWLinkedTask\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(fromID));
        query.addParameter("toID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(toID));
        query.setResultClass(PHSManualUWLinkedTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.PHSManualUWLinkedTask> getPHSManualUWLinkedTaskObjects(long fromID, long toID)
    {
        String queryText = "select * from \"PHSManualUWLinkedTask\" where \"ID\" between :fromID and :toID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(fromID));
        query.addParameter("toID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(toID));
        query.setResultClass(PHSManualUWLinkedTask.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.PHSManualUWLinkedTask> getPreviousPHSManualUWLinkedTaskObjects(long ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"PHSManualUWLinkedTask\" where (\"ID\" < :ID) order by \"ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ID", "PHSManualUWLinkedTask.ID", QueryObject.PARAM_INT, new Long(ID));//NOPMD
        query.setResultClass(PHSManualUWLinkedTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }


}
