/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class PHSManualUWLinkedTask extends PHSManualUWLinkedTaskBase
{
    public PHSManualUWLinkedTask()
    {
        this((BusObjectConfig)null);
    }

    public PHSManualUWLinkedTask(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.PHSManualUWLinkedTask> getUWPHSUnprocessedTasks()
    {
        String queryText = "select * from PHSManualUWLinkedTask where ProcessedFlag='N'";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(PHSManualUWLinkedTask.class);
        return query.getObjects();
    }

}
