/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_Worksite_OrderRequirement extends tbl_Worksite_OrderRequirementBase
{
    public tbl_Worksite_OrderRequirement()
    {
        this((BusObjectConfig)null);
    }

    public tbl_Worksite_OrderRequirement(BusObjectConfig config)
    {
        super(config);
    }

}
