/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class tbl_underwriting_CanadaFollowUP extends tbl_underwriting_CanadaFollowUPBase
{
    public tbl_underwriting_CanadaFollowUP()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_CanadaFollowUP(BusObjectConfig config)
    {
        super(config);
    }

    public static com.cica.uw.tbl_underwriting_CanadaFollowUP getCanadaRequirementDetails(String requirementType)
    {
       String queryText="select * from tbl_underwriting_CanadaFollowUP where requirmentType=:reqType";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("reqType", "tbl_underwriting_CanadaFollowUP.requirmentType", QueryObject.PARAM_STRING, requirementType);
        query.setResultClass(tbl_underwriting_CanadaFollowUP.class);
        return (tbl_underwriting_CanadaFollowUP)query.getObject();
    }

}
