/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_letterid extends tbl_underwriting_letteridBase
{
    public tbl_underwriting_letterid()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_letterid(BusObjectConfig config)
    {
        super(config);
    }

}
