/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_UWCaseBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_case_id = "case_id";
    public final static String ATTR_policy_number = "policy_number";
    public final static String ATTR_process_type = "process_type";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_UWCase.class);
            s_classInfo.setTableName("tbl_UWCase");
            s_classInfo.setUIDElements(new String[]{ATTR_case_id});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_case_id);
                ai.setJavaName(ATTR_case_id);
                ai.setColumnName(ATTR_case_id);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_case_id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_policy_number);
                ai.setJavaName(ATTR_policy_number);
                ai.setColumnName(ATTR_policy_number);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_policy_number);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_process_type);
                ai.setJavaName(ATTR_process_type);
                ai.setColumnName(ATTR_process_type);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_process_type);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_UWCaseBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getCase_id()
    {
        return getIntProperty(ATTR_case_id);
    }

    public void setCase_id(int value)
    {
        setProperty(ATTR_case_id, value, 0);
    }

    public String getPolicy_number()
    {
        return getStringProperty(ATTR_policy_number);
    }

    public void setPolicy_number(String value)
    {
        setProperty(ATTR_policy_number, value, 0);
    }

    public String getProcess_type()
    {
        return getStringProperty(ATTR_process_type);
    }

    public void setProcess_type(String value)
    {
        setProperty(ATTR_process_type, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.tbl_UWCase> getNextTbl_UWCaseObjects(int Case_id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_UWCase\" where (\"case_id\" > :Case_id) order by \"case_id\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Case_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(Case_id));//NOPMD
        query.setResultClass(tbl_UWCase.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_UWCase> getPreviousTbl_UWCaseObjects(int Case_id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_UWCase\" where (\"case_id\" < :Case_id) order by \"case_id\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Case_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(Case_id));//NOPMD
        query.setResultClass(tbl_UWCase.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tbl_UWCase getTbl_UWCaseObject(int Case_id)
    {
        String queryText = "select * from \"tbl_UWCase\" where \"case_id\" = :Case_id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Case_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(Case_id));//NOPMD
        query.setResultClass(tbl_UWCase.class);
        return (tbl_UWCase)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tbl_UWCase> getTbl_UWCaseObjects(int fromCase_id, int toCase_id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_UWCase\" where \"case_id\" between :fromCase_id and :toCase_id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCase_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(fromCase_id));
        query.addParameter("toCase_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(toCase_id));
        query.setResultClass(tbl_UWCase.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_UWCase> getTbl_UWCaseObjects(int fromCase_id, int toCase_id)
    {
        String queryText = "select * from \"tbl_UWCase\" where \"case_id\" between :fromCase_id and :toCase_id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromCase_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(fromCase_id));
        query.addParameter("toCase_id", "tbl_UWCase.case_id", QueryObject.PARAM_INT, new Integer(toCase_id));
        query.setResultClass(tbl_UWCase.class);
        return query.getObjects();
    }

}
