/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_underwriting_tasklistBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_id = "id";
    public final static String ATTR_taskid = "taskid";
    public final static String ATTR_application_number = "application_number";
    public final static String ATTR_task_type = "task_type";
    public final static String ATTR_entry_date = "entry_date";
    public final static String ATTR_update_date = "update_date";
    public final static String ATTR_task_status = "task_status";
    public final static String ATTR_task_comments = "task_comments";
    public final static String ATTR_case_id = "case_id";
    public final static String ATTR_owner = "owner";
    public final static String ATTR_task_completion_date = "task_completion_date";
    public final static String ATTR_task_save_reason = "task_save_reason";
    public final static String ATTR_task_due_date = "task_due_date";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_underwriting_tasklist.class);
            s_classInfo.setTableName("tbl_underwriting_tasklist");
            s_classInfo.setUIDElements(new String[]{ATTR_id});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_id);
                ai.setJavaName(ATTR_id);
                ai.setColumnName(ATTR_id);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_taskid);
                ai.setJavaName(ATTR_taskid);
                ai.setColumnName(ATTR_taskid);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_taskid);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_application_number);
                ai.setJavaName(ATTR_application_number);
                ai.setColumnName(ATTR_application_number);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_application_number);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_type);
                ai.setJavaName(ATTR_task_type);
                ai.setColumnName(ATTR_task_type);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_task_type);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_entry_date);
                ai.setJavaName(ATTR_entry_date);
                ai.setColumnName(ATTR_entry_date);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_update_date);
                ai.setJavaName(ATTR_update_date);
                ai.setColumnName(ATTR_update_date);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_status);
                ai.setJavaName(ATTR_task_status);
                ai.setColumnName(ATTR_task_status);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_task_status);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_comments);
                ai.setJavaName(ATTR_task_comments);
                ai.setColumnName(ATTR_task_comments);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_task_comments);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_case_id);
                ai.setJavaName(ATTR_case_id);
                ai.setColumnName(ATTR_case_id);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_case_id);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_owner);
                ai.setJavaName(ATTR_owner);
                ai.setColumnName(ATTR_owner);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_owner);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_completion_date);
                ai.setJavaName(ATTR_task_completion_date);
                ai.setColumnName(ATTR_task_completion_date);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_save_reason);
                ai.setJavaName(ATTR_task_save_reason);
                ai.setColumnName(ATTR_task_save_reason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_task_save_reason);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_due_date);
                ai.setJavaName(ATTR_task_due_date);
                ai.setColumnName(ATTR_task_due_date);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_underwriting_tasklistBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getId()
    {
        return getLongProperty(ATTR_id);
    }

    public void setId(long value)
    {
        setProperty(ATTR_id, value, 0);
    }

    public String getTaskid()
    {
        return getStringProperty(ATTR_taskid);
    }

    public void setTaskid(String value)
    {
        setProperty(ATTR_taskid, value, 0);
    }

    public String getApplication_number()
    {
        return getStringProperty(ATTR_application_number);
    }

    public void setApplication_number(String value)
    {
        setProperty(ATTR_application_number, value, 0);
    }

    public String getTask_type()
    {
        return getStringProperty(ATTR_task_type);
    }

    public void setTask_type(String value)
    {
        setProperty(ATTR_task_type, value, 0);
    }

    public java.util.Date getEntry_date()
    {
        return getDateTimestampProperty(ATTR_entry_date);
    }

    public void setEntry_date(java.util.Date value)
    {
        setProperty(ATTR_entry_date, value, 0);
    }

    public java.util.Date getUpdate_date()
    {
        return getDateTimestampProperty(ATTR_update_date);
    }

    public void setUpdate_date(java.util.Date value)
    {
        setProperty(ATTR_update_date, value, 0);
    }

    public String getTask_status()
    {
        return getStringProperty(ATTR_task_status);
    }

    public void setTask_status(String value)
    {
        setProperty(ATTR_task_status, value, 0);
    }

    public String getTask_comments()
    {
        return getStringProperty(ATTR_task_comments);
    }

    public void setTask_comments(String value)
    {
        setProperty(ATTR_task_comments, value, 0);
    }

    public String getCase_id()
    {
        return getStringProperty(ATTR_case_id);
    }

    public void setCase_id(String value)
    {
        setProperty(ATTR_case_id, value, 0);
    }

    public String getOwner()
    {
        return getStringProperty(ATTR_owner);
    }

    public void setOwner(String value)
    {
        setProperty(ATTR_owner, value, 0);
    }

    public java.util.Date getTask_completion_date()
    {
        return getDateTimestampProperty(ATTR_task_completion_date);
    }

    public void setTask_completion_date(java.util.Date value)
    {
        setProperty(ATTR_task_completion_date, value, 0);
    }

    public String getTask_save_reason()
    {
        return getStringProperty(ATTR_task_save_reason);
    }

    public void setTask_save_reason(String value)
    {
        setProperty(ATTR_task_save_reason, value, 0);
    }

    public java.util.Date getTask_due_date()
    {
        return getDateTimestampProperty(ATTR_task_due_date);
    }

    public void setTask_due_date(java.util.Date value)
    {
        setProperty(ATTR_task_due_date, value, 0);
    }


    public static BusObjectIterator<com.cica.uw.tbl_underwriting_tasklist> getNextTbl_underwriting_tasklistObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_tasklist\" where (\"id\" > :Id) order by \"id\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(tbl_underwriting_tasklist.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_tasklist> getPreviousTbl_underwriting_tasklistObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_tasklist\" where (\"id\" < :Id) order by \"id\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(tbl_underwriting_tasklist.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tbl_underwriting_tasklist getTbl_underwriting_tasklistObject(long Id)
    {
        String queryText = "select * from \"tbl_underwriting_tasklist\" where \"id\" = :Id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(tbl_underwriting_tasklist.class);
        return (tbl_underwriting_tasklist)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_tasklist> getTbl_underwriting_tasklistObjects(long fromId, long toId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_tasklist\" where \"id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(tbl_underwriting_tasklist.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_tasklist> getTbl_underwriting_tasklistObjects(long fromId, long toId)
    {
        String queryText = "select * from \"tbl_underwriting_tasklist\" where \"id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "tbl_underwriting_tasklist.id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(tbl_underwriting_tasklist.class);
        return query.getObjects();
    }

}
