/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_UWCase extends tbl_UWCaseBase
{
    public tbl_UWCase()
    {
        this((BusObjectConfig)null);
    }

    public tbl_UWCase(BusObjectConfig config)
    {
        super(config);
    }

}
