/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_agent extends tbl_underwriting_agentBase
{
    public tbl_underwriting_agent()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_agent(BusObjectConfig config)
    {
        super(config);
    }

}
