/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_benefit extends tbl_underwriting_benefitBase
{
    public tbl_underwriting_benefit()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_benefit(BusObjectConfig config)
    {
        super(config);
    }

}
