/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_reason extends tbl_underwriting_reasonBase
{
    public tbl_underwriting_reason()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_reason(BusObjectConfig config)
    {
        super(config);
    }

}
