/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;

public class tbl_underwritring_Prod_vs_Req extends tbl_underwritring_Prod_vs_ReqBase
{
    public tbl_underwritring_Prod_vs_Req()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwritring_Prod_vs_Req(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwritring_Prod_vs_Req> getUWProdReqNonVendor(String prodName, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText="select req_Mst_id from tbl_underwritring_Prod_vs_Req where prodname=:prodName and req_Mst_id in (select req_Mst_id from tbl_underwriting_reqMst where vendor_flag='Non-Vendor')";
        QueryObject query=new QueryObject(queryText);
        query.addParameter("prodName", "tbl_underwritring_Prod_vs_Req.prodname",QueryObject.PARAM_STRING, prodName);
        query.setResultClass(tbl_underwritring_Prod_vs_Req.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwritring_Prod_vs_Req> getUWProdReqVendor(String prodName, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText="select req_Mst_id from tbl_underwritring_Prod_vs_Req where prodname=:prodName and req_Mst_id in (select req_Mst_id from tbl_underwriting_reqMst where vendor_flag='Vendor')";
        QueryObject query=new QueryObject(queryText);
        query.addParameter("prodName", "tbl_underwritring_Prod_vs_Req.prodname",QueryObject.PARAM_STRING, prodName);
        query.setResultClass(tbl_underwritring_Prod_vs_Req.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
