/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_reasoncode extends tbl_underwriting_reasoncodeBase
{
    public tbl_underwriting_reasoncode()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_reasoncode(BusObjectConfig config)
    {
        super(config);
    }

}
