/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_underwriting_medical_conditionBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_Objid = "Objid";
    public final static String ATTR_System = "System";
    public final static String ATTR_Condition = "Condition";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_underwriting_medical_condition.class);
            s_classInfo.setTableName("tbl_underwriting_medical_condition");
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Objid);
                ai.setJavaName(ATTR_Objid);
                ai.setColumnName(ATTR_Objid);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_Objid);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_System);
                ai.setJavaName(ATTR_System);
                ai.setColumnName(ATTR_System);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_System);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Condition);
                ai.setJavaName(ATTR_Condition);
                ai.setColumnName(ATTR_Condition);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Condition);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_underwriting_medical_conditionBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getObjid()
    {
        return getIntProperty(ATTR_Objid);
    }

    public void setObjid(int value)
    {
        setProperty(ATTR_Objid, value, 0);
    }

    public String getSystem()
    {
        return getStringProperty(ATTR_System);
    }

    public void setSystem(String value)
    {
        setProperty(ATTR_System, value, 0);
    }

    public String getCondition()
    {
        return getStringProperty(ATTR_Condition);
    }

    public void setCondition(String value)
    {
        setProperty(ATTR_Condition, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_medical_condition> GetMedicalCondition(String system)
    {
        String queryText = "select * from \"tbl_underwriting_medical_condition\" where \"System\" = :system";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("system", "tbl_underwriting_medical_condition.System", QueryObject.PARAM_STRING, system);//NOPMD
        query.setResultClass(tbl_underwriting_medical_condition.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_medical_condition> GetMedicalConditionValues()
    {
        String queryText = "select * from \"tbl_underwriting_medical_condition\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tbl_underwriting_medical_condition.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_medical_condition> getTbl_underwriting_medical_conditionObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_medical_condition\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tbl_underwriting_medical_condition.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_medical_condition> getTbl_underwriting_medical_conditionObjects()
    {
        String queryText = "select * from \"tbl_underwriting_medical_condition\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tbl_underwriting_medical_condition.class);
        return query.getObjects();
    }

}
