/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_coveragetype extends tbl_underwriting_coveragetypeBase
{
    public tbl_underwriting_coveragetype()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_coveragetype(BusObjectConfig config)
    {
        super(config);
    }

}
