/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_pi_contact extends tbl_pi_contactBase
{
    public tbl_pi_contact()
    {
        this((BusObjectConfig)null);
    }

    public tbl_pi_contact(BusObjectConfig config)
    {
        super(config);
    }

}
