/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_pi_addressBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_objid = "objid";
    public final static String ATTR_dev = "dev";
    public final static String ATTR_x_address = "x_address";
    public final static String ATTR_x_address2 = "x_address2";
    public final static String ATTR_x_city = "x_city";
    public final static String ATTR_x_state = "x_state";
    public final static String ATTR_x_zip = "x_zip";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_pi_address.class);
            s_classInfo.setTableName("tbl_pi_address");
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_objid);
                ai.setJavaName(ATTR_objid);
                ai.setColumnName(ATTR_objid);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_objid);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_dev);
                ai.setJavaName(ATTR_dev);
                ai.setColumnName(ATTR_dev);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_dev);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_x_address);
                ai.setJavaName(ATTR_x_address);
                ai.setColumnName(ATTR_x_address);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_x_address);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_x_address2);
                ai.setJavaName(ATTR_x_address2);
                ai.setColumnName(ATTR_x_address2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_x_address2);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_x_city);
                ai.setJavaName(ATTR_x_city);
                ai.setColumnName(ATTR_x_city);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_x_city);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_x_state);
                ai.setJavaName(ATTR_x_state);
                ai.setColumnName(ATTR_x_state);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_x_state);
                v.setMaxLength(2);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_x_zip);
                ai.setJavaName(ATTR_x_zip);
                ai.setColumnName(ATTR_x_zip);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_x_zip);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_pi_addressBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getObjid()
    {
        return getIntProperty(ATTR_objid);
    }

    public void setObjid(int value)
    {
        setProperty(ATTR_objid, value, 0);
    }

    public int getDev()
    {
        return getIntProperty(ATTR_dev);
    }

    public void setDev(int value)
    {
        setProperty(ATTR_dev, value, 0);
    }

    public String getX_address()
    {
        return getStringProperty(ATTR_x_address);
    }

    public void setX_address(String value)
    {
        setProperty(ATTR_x_address, value, 0);
    }

    public String getX_address2()
    {
        return getStringProperty(ATTR_x_address2);
    }

    public void setX_address2(String value)
    {
        setProperty(ATTR_x_address2, value, 0);
    }

    public String getX_city()
    {
        return getStringProperty(ATTR_x_city);
    }

    public void setX_city(String value)
    {
        setProperty(ATTR_x_city, value, 0);
    }

    public String getX_state()
    {
        return getStringProperty(ATTR_x_state);
    }

    public void setX_state(String value)
    {
        setProperty(ATTR_x_state, value, 0);
    }

    public String getX_zip()
    {
        return getStringProperty(ATTR_x_zip);
    }

    public void setX_zip(String value)
    {
        setProperty(ATTR_x_zip, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.tbl_pi_address> GetBeneficiaryAddress(int objid)
    {
        String queryText = "select * from \"tbl_pi_address\" where \"objid\" = :objid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("objid", "tbl_pi_address.objid", QueryObject.PARAM_INT, new Integer(objid));//NOPMD
        query.setResultClass(tbl_pi_address.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_pi_address> getTbl_pi_addressObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_pi_address\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tbl_pi_address.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_pi_address> getTbl_pi_addressObjects()
    {
        String queryText = "select * from \"tbl_pi_address\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tbl_pi_address.class);
        return query.getObjects();
    }

}
