/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;

public class tbl_underwriting_dependent extends tbl_underwriting_dependentBase
{
    public tbl_underwriting_dependent()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_dependent(BusObjectConfig config)
    {
        super(config);
    }

  public static BusObjectIterator<com.cordys.cpc.bsf.busobject.BusObject> getDependentListMethod(String PolicyNo)
    {
        String queryText =   
        "SELECT  value FROM ( SELECT CAST('Select ' as VARCHAR(100) )as col1,  isnull( case when ( (u.last_name !='' )and (u.last_name is not null) "+
        "and (u.first_name!='') and (u.first_name is not null) )  then  CAST('Primary Insured: ' + u.last_name + ' ' + u.first_name as VARCHAR(100))end, null) as col2, "+   
        "isnull( case when ( (d.spouse_last_name !='' )and (d.spouse_last_name is not null)  and (d.spouse_first_name!='') and (d.spouse_first_name is not null) )  then "+
        "CAST('Spouse: ' + d.spouse_last_name + ' ' + d.spouse_first_name as VARCHAR(100)) end, null) as col3, isnull( case when ( (d.child1_last_name !='' )and (d.child1_last_name is not null) "+
        "and (d.child1_first_name!='') and (d.child1_first_name is not null) )  then  CAST('Dependent Child 1: ' + d.child1_last_name + ' ' + d.child1_first_name as VARCHAR(100)) end, null) as col4, "+   
        "isnull( case when ( (d.child2_last_name !='' )and (d.child2_last_name is not null) and (d.child2_first_name!='') and (d.child2_first_name is not null) )  then "+
        "CAST('Dependent Child 2: ' + d.child2_last_name + ' ' + d.child2_first_name as VARCHAR(100)) end, null) as col5, isnull( case when ( (d.child3_last_name !='' )and (d.child3_last_name is not null) "+
        "and (d.child3_first_name!='') and (d.child3_first_name is not null) )  then CAST('Dependent Child 3: ' + d.child3_last_name + ' ' + d.child3_first_name as VARCHAR(100)) end, null) as col6, "+    
        "isnull( case when ( (d.child4_last_name !='' )and (d.child4_last_name is not null) and (d.child4_first_name!='') and (d.child4_first_name is not null) )  then "+
        "CAST('Dependent Child 4: ' + d.child4_last_name + ' ' + d.child4_first_name as VARCHAR(100)) end, null) as col7, isnull( case when ( (d.child5_last_name !='' )and (d.child5_last_name is not null) "+
        "and (d.child5_first_name!='') and (d.child5_first_name is not null) )  then CAST('Dependent Child 5: ' + d.child5_last_name + ' ' + d.child5_first_name as VARCHAR(100)) end , null) as col8, "+  
        "isnull( case when ( (d.child6_last_name !='' )and (d.child6_last_name is not null) and (d.child6_first_name!='') and (d.child6_first_name is not null) )  then "+
        "CAST('Dependent Child 6: ' + d.child6_last_name + ' ' + d.child6_first_name as VARCHAR(100)) end, null) as col9, isnull( case when ( (d.child7_last_name !='' )and (d.child7_last_name is not null) "+
        "and (d.child7_first_name!='') and (d.child7_first_name is not null) )  then CAST('Dependent Child 7: ' + d.child7_last_name + ' ' + d.child7_first_name as VARCHAR(100)) end, null) as col10, "+  
        "isnull( case when ( (d.child8_last_name !='' )and (d.child8_last_name is not null)  and (d.child8_first_name!='') and (d.child8_first_name is not null) )  then "+
        "CAST('Dependent Child 8: ' + d.child8_last_name + ' ' + d.child8_first_name as VARCHAR(100)) end, null) as col11, CAST('Other ' as VARCHAR(100) )as col12 "+
        "FROM tbl_underwriting_dependent d, tbl_underwriting u where d.policy_number = u.policy_number and "+
        "d.policy_number = :PolicyNo ) p UNPIVOT (value FOR col IN  (col1, col2, col3, col4,col5, col6, col7, col8,col9, col10, col11, col12)) AS unpvt";
        QueryObject query = new QueryObject(queryText);
         query.addParameter("PolicyNo", "tbl_underwriting_dependent.policy_number", QueryObject.PARAM_STRING, PolicyNo);//NOPMD
        query.setResultClass( tbl_underwriting_dependent.class);
        return query.getObjects();
    }

}

