/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_underwriting_case extends tbl_underwriting_caseBase
{
    public tbl_underwriting_case()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_case(BusObjectConfig config)
    {
        super(config);
    }

}
