/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_underwriting_NonVendorOrderRequirementTaskBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_tableid = "tableid";
    public final static String ATTR_case_id = "case_id";
    public final static String ATTR_CompletedRequirementFlag = "CompletedRequirementFlag";
    public final static String ATTR_FollowUpCounter = "FollowUpCounter";
    public final static String ATTR_PersonalDetails = "PersonalDetails";
    public final static String ATTR_RequirementType = "RequirementType";
    public final static String ATTR_ApplicantRequiredDetails = "ApplicantRequiredDetails";
    public final static String ATTR_InhousePHIRelatedDetails = "InhousePHIRelatedDetails";
    public final static String ATTR_RxRequiredDetails = "RxRequiredDetails";
    public final static String ATTR_MillimanRxDetails = "MillimanRxDetails";
    public final static String ATTR_OverageDependentForm = "OverageDependentForm";
    public final static String ATTR_AgentDetails = "AgentDetails";
    public final static String ATTR_NewBenefitsOrCoverage = "NewBenefitsOrCoverage";
    public final static String ATTR_ErrorAuditMessages = "ErrorAuditMessages";
    public final static String ATTR_ClaimNumber = "ClaimNumber";
    public final static String ATTR_OtherDetails = "OtherDetails";
    public final static String ATTR_Toolkits = "Toolkits";
    public final static String ATTR_ConductEndingScript = "ConductEndingScript";
    public final static String ATTR_Checklist = "Checklist";
    public final static String ATTR_req_id = "req_id";
    public final static String ATTR_FollowupReason = "FollowupReason";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_underwriting_NonVendorOrderRequirementTask.class);
            s_classInfo.setTableName("tbl_underwriting_NonVendorOrderRequirementTask");
            s_classInfo.setUIDElements(new String[]{ATTR_tableid});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_tableid);
                ai.setJavaName(ATTR_tableid);
                ai.setColumnName(ATTR_tableid);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_tableid);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_case_id);
                ai.setJavaName(ATTR_case_id);
                ai.setColumnName(ATTR_case_id);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_case_id);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompletedRequirementFlag);
                ai.setJavaName(ATTR_CompletedRequirementFlag);
                ai.setColumnName(ATTR_CompletedRequirementFlag);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompletedRequirementFlag);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpCounter);
                ai.setJavaName(ATTR_FollowUpCounter);
                ai.setColumnName(ATTR_FollowUpCounter);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FollowUpCounter);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PersonalDetails);
                ai.setJavaName(ATTR_PersonalDetails);
                ai.setColumnName(ATTR_PersonalDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PersonalDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequirementType);
                ai.setJavaName(ATTR_RequirementType);
                ai.setColumnName(ATTR_RequirementType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequirementType);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ApplicantRequiredDetails);
                ai.setJavaName(ATTR_ApplicantRequiredDetails);
                ai.setColumnName(ATTR_ApplicantRequiredDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ApplicantRequiredDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_InhousePHIRelatedDetails);
                ai.setJavaName(ATTR_InhousePHIRelatedDetails);
                ai.setColumnName(ATTR_InhousePHIRelatedDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_InhousePHIRelatedDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RxRequiredDetails);
                ai.setJavaName(ATTR_RxRequiredDetails);
                ai.setColumnName(ATTR_RxRequiredDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RxRequiredDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MillimanRxDetails);
                ai.setJavaName(ATTR_MillimanRxDetails);
                ai.setColumnName(ATTR_MillimanRxDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MillimanRxDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OverageDependentForm);
                ai.setJavaName(ATTR_OverageDependentForm);
                ai.setColumnName(ATTR_OverageDependentForm);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OverageDependentForm);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AgentDetails);
                ai.setJavaName(ATTR_AgentDetails);
                ai.setColumnName(ATTR_AgentDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AgentDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_NewBenefitsOrCoverage);
                ai.setJavaName(ATTR_NewBenefitsOrCoverage);
                ai.setColumnName(ATTR_NewBenefitsOrCoverage);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_NewBenefitsOrCoverage);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ErrorAuditMessages);
                ai.setJavaName(ATTR_ErrorAuditMessages);
                ai.setColumnName(ATTR_ErrorAuditMessages);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ErrorAuditMessages);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ClaimNumber);
                ai.setJavaName(ATTR_ClaimNumber);
                ai.setColumnName(ATTR_ClaimNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ClaimNumber);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OtherDetails);
                ai.setJavaName(ATTR_OtherDetails);
                ai.setColumnName(ATTR_OtherDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OtherDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Toolkits);
                ai.setJavaName(ATTR_Toolkits);
                ai.setColumnName(ATTR_Toolkits);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Toolkits);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ConductEndingScript);
                ai.setJavaName(ATTR_ConductEndingScript);
                ai.setColumnName(ATTR_ConductEndingScript);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ConductEndingScript);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Checklist);
                ai.setJavaName(ATTR_Checklist);
                ai.setColumnName(ATTR_Checklist);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Checklist);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_req_id);
                ai.setJavaName(ATTR_req_id);
                ai.setColumnName(ATTR_req_id);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_req_id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowupReason);
                ai.setJavaName(ATTR_FollowupReason);
                ai.setColumnName(ATTR_FollowupReason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FollowupReason);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_underwriting_NonVendorOrderRequirementTaskBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getTableid()
    {
        return getIntProperty(ATTR_tableid);
    }

    public void setTableid(int value)
    {
        setProperty(ATTR_tableid, value, 0);
    }

    public String getCase_id()
    {
        return getStringProperty(ATTR_case_id);
    }

    public void setCase_id(String value)
    {
        setProperty(ATTR_case_id, value, 0);
    }

    public String getCompletedRequirementFlag()
    {
        return getStringProperty(ATTR_CompletedRequirementFlag);
    }

    public void setCompletedRequirementFlag(String value)
    {
        setProperty(ATTR_CompletedRequirementFlag, value, 0);
    }

    public String getFollowUpCounter()
    {
        return getStringProperty(ATTR_FollowUpCounter);
    }

    public void setFollowUpCounter(String value)
    {
        setProperty(ATTR_FollowUpCounter, value, 0);
    }

    public String getPersonalDetails()
    {
        return getStringProperty(ATTR_PersonalDetails);
    }

    public void setPersonalDetails(String value)
    {
        setProperty(ATTR_PersonalDetails, value, 0);
    }

    public String getRequirementType()
    {
        return getStringProperty(ATTR_RequirementType);
    }

    public void setRequirementType(String value)
    {
        setProperty(ATTR_RequirementType, value, 0);
    }

    public String getApplicantRequiredDetails()
    {
        return getStringProperty(ATTR_ApplicantRequiredDetails);
    }

    public void setApplicantRequiredDetails(String value)
    {
        setProperty(ATTR_ApplicantRequiredDetails, value, 0);
    }

    public String getInhousePHIRelatedDetails()
    {
        return getStringProperty(ATTR_InhousePHIRelatedDetails);
    }

    public void setInhousePHIRelatedDetails(String value)
    {
        setProperty(ATTR_InhousePHIRelatedDetails, value, 0);
    }

    public String getRxRequiredDetails()
    {
        return getStringProperty(ATTR_RxRequiredDetails);
    }

    public void setRxRequiredDetails(String value)
    {
        setProperty(ATTR_RxRequiredDetails, value, 0);
    }

    public String getMillimanRxDetails()
    {
        return getStringProperty(ATTR_MillimanRxDetails);
    }

    public void setMillimanRxDetails(String value)
    {
        setProperty(ATTR_MillimanRxDetails, value, 0);
    }

    public String getOverageDependentForm()
    {
        return getStringProperty(ATTR_OverageDependentForm);
    }

    public void setOverageDependentForm(String value)
    {
        setProperty(ATTR_OverageDependentForm, value, 0);
    }

    public String getAgentDetails()
    {
        return getStringProperty(ATTR_AgentDetails);
    }

    public void setAgentDetails(String value)
    {
        setProperty(ATTR_AgentDetails, value, 0);
    }

    public String getNewBenefitsOrCoverage()
    {
        return getStringProperty(ATTR_NewBenefitsOrCoverage);
    }

    public void setNewBenefitsOrCoverage(String value)
    {
        setProperty(ATTR_NewBenefitsOrCoverage, value, 0);
    }

    public String getErrorAuditMessages()
    {
        return getStringProperty(ATTR_ErrorAuditMessages);
    }

    public void setErrorAuditMessages(String value)
    {
        setProperty(ATTR_ErrorAuditMessages, value, 0);
    }

    public String getClaimNumber()
    {
        return getStringProperty(ATTR_ClaimNumber);
    }

    public void setClaimNumber(String value)
    {
        setProperty(ATTR_ClaimNumber, value, 0);
    }

    public String getOtherDetails()
    {
        return getStringProperty(ATTR_OtherDetails);
    }

    public void setOtherDetails(String value)
    {
        setProperty(ATTR_OtherDetails, value, 0);
    }

    public String getToolkits()
    {
        return getStringProperty(ATTR_Toolkits);
    }

    public void setToolkits(String value)
    {
        setProperty(ATTR_Toolkits, value, 0);
    }

    public String getConductEndingScript()
    {
        return getStringProperty(ATTR_ConductEndingScript);
    }

    public void setConductEndingScript(String value)
    {
        setProperty(ATTR_ConductEndingScript, value, 0);
    }

    public String getChecklist()
    {
        return getStringProperty(ATTR_Checklist);
    }

    public void setChecklist(String value)
    {
        setProperty(ATTR_Checklist, value, 0);
    }

    public long getReq_id()
    {
        return getLongProperty(ATTR_req_id);
    }

    public void setReq_id(long value)
    {
        setProperty(ATTR_req_id, value, 0);
    }

    public String getFollowupReason()
    {
        return getStringProperty(ATTR_FollowupReason);
    }

    public void setFollowupReason(String value)
    {
        setProperty(ATTR_FollowupReason, value, 0);
    }


    public static BusObjectIterator<com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask> getNextTbl_underwriting_NonVendorOrderRequirementTaskObjects(int Tableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_NonVendorOrderRequirementTask\" where (\"tableid\" > :Tableid) order by \"tableid\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(Tableid));//NOPMD
        query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask> getPreviousTbl_underwriting_NonVendorOrderRequirementTaskObjects(int Tableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_NonVendorOrderRequirementTask\" where (\"tableid\" < :Tableid) order by \"tableid\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(Tableid));//NOPMD
        query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask getTbl_underwriting_NonVendorOrderRequirementTaskObject(int Tableid)
    {
        String queryText = "select * from \"tbl_underwriting_NonVendorOrderRequirementTask\" where \"tableid\" = :Tableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(Tableid));//NOPMD
        query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
        return (tbl_underwriting_NonVendorOrderRequirementTask)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask> getTbl_underwriting_NonVendorOrderRequirementTaskObjects(int fromTableid, int toTableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_underwriting_NonVendorOrderRequirementTask\" where \"tableid\" between :fromTableid and :toTableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromTableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(fromTableid));
        query.addParameter("toTableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(toTableid));
        query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask> getTbl_underwriting_NonVendorOrderRequirementTaskObjects(int fromTableid, int toTableid)
    {
        String queryText = "select * from \"tbl_underwriting_NonVendorOrderRequirementTask\" where \"tableid\" between :fromTableid and :toTableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromTableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(fromTableid));
        query.addParameter("toTableid", "tbl_underwriting_NonVendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Integer(toTableid));
        query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
        return query.getObjects();
    }

}
