/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_part_num extends tbl_part_numBase
{
    public tbl_part_num()
    {
        this((BusObjectConfig)null);
    }

    public tbl_part_num(BusObjectConfig config)
    {
        super(config);
    }

}
