/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tbl_Worksite_VendorOrderRequirementTaskBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_tableid = "tableid";
    public final static String ATTR_case_id = "case_id";
    public final static String ATTR_task_id = "task_id";
    public final static String ATTR_PersonalDetails = "PersonalDetails";
    public final static String ATTR_RequirementType = "RequirementType";
    public final static String ATTR_OtherDetails = "OtherDetails";
    public final static String ATTR_OrderedRequirement = "OrderedRequirement";
    public final static String ATTR_CompanyPolicyNo = "CompanyPolicyNo";
    public final static String ATTR_Products = "Products";
    public final static String ATTR_CheckLists = "CheckLists";
    public final static String ATTR_CompletedRequirementFlag = "CompletedRequirementFlag";
    public final static String ATTR_RequirementCount = "RequirementCount";
    public final static String ATTR_RequirementStatus = "RequirementStatus";
    public final static String ATTR_MRSPKID = "MRSPKID";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tbl_Worksite_VendorOrderRequirementTask.class);
            s_classInfo.setTableName("tbl_Worksite_VendorOrderRequirementTask");
            s_classInfo.setUIDElements(new String[]{ATTR_tableid});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_tableid);
                ai.setJavaName(ATTR_tableid);
                ai.setColumnName(ATTR_tableid);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_tableid);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_case_id);
                ai.setJavaName(ATTR_case_id);
                ai.setColumnName(ATTR_case_id);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_case_id);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_task_id);
                ai.setJavaName(ATTR_task_id);
                ai.setColumnName(ATTR_task_id);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_task_id);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PersonalDetails);
                ai.setJavaName(ATTR_PersonalDetails);
                ai.setColumnName(ATTR_PersonalDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PersonalDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequirementType);
                ai.setJavaName(ATTR_RequirementType);
                ai.setColumnName(ATTR_RequirementType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequirementType);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OtherDetails);
                ai.setJavaName(ATTR_OtherDetails);
                ai.setColumnName(ATTR_OtherDetails);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OtherDetails);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrderedRequirement);
                ai.setJavaName(ATTR_OrderedRequirement);
                ai.setColumnName(ATTR_OrderedRequirement);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_OrderedRequirement);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompanyPolicyNo);
                ai.setJavaName(ATTR_CompanyPolicyNo);
                ai.setColumnName(ATTR_CompanyPolicyNo);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompanyPolicyNo);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Products);
                ai.setJavaName(ATTR_Products);
                ai.setColumnName(ATTR_Products);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Products);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CheckLists);
                ai.setJavaName(ATTR_CheckLists);
                ai.setColumnName(ATTR_CheckLists);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CheckLists);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompletedRequirementFlag);
                ai.setJavaName(ATTR_CompletedRequirementFlag);
                ai.setColumnName(ATTR_CompletedRequirementFlag);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompletedRequirementFlag);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequirementCount);
                ai.setJavaName(ATTR_RequirementCount);
                ai.setColumnName(ATTR_RequirementCount);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_RequirementCount);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequirementStatus);
                ai.setJavaName(ATTR_RequirementStatus);
                ai.setColumnName(ATTR_RequirementStatus);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequirementStatus);
                v.setMaxLength(2147483647);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MRSPKID);
                ai.setJavaName(ATTR_MRSPKID);
                ai.setColumnName(ATTR_MRSPKID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MRSPKID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tbl_Worksite_VendorOrderRequirementTaskBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getTableid()
    {
        return getLongProperty(ATTR_tableid);
    }

    public void setTableid(long value)
    {
        setProperty(ATTR_tableid, value, 0);
    }

    public String getCase_id()
    {
        return getStringProperty(ATTR_case_id);
    }

    public void setCase_id(String value)
    {
        setProperty(ATTR_case_id, value, 0);
    }

    public String getTask_id()
    {
        return getStringProperty(ATTR_task_id);
    }

    public void setTask_id(String value)
    {
        setProperty(ATTR_task_id, value, 0);
    }

    public String getPersonalDetails()
    {
        return getStringProperty(ATTR_PersonalDetails);
    }

    public void setPersonalDetails(String value)
    {
        setProperty(ATTR_PersonalDetails, value, 0);
    }

    public String getRequirementType()
    {
        return getStringProperty(ATTR_RequirementType);
    }

    public void setRequirementType(String value)
    {
        setProperty(ATTR_RequirementType, value, 0);
    }

    public String getOtherDetails()
    {
        return getStringProperty(ATTR_OtherDetails);
    }

    public void setOtherDetails(String value)
    {
        setProperty(ATTR_OtherDetails, value, 0);
    }

    public String getOrderedRequirement()
    {
        return getStringProperty(ATTR_OrderedRequirement);
    }

    public void setOrderedRequirement(String value)
    {
        setProperty(ATTR_OrderedRequirement, value, 0);
    }

    public String getCompanyPolicyNo()
    {
        return getStringProperty(ATTR_CompanyPolicyNo);
    }

    public void setCompanyPolicyNo(String value)
    {
        setProperty(ATTR_CompanyPolicyNo, value, 0);
    }

    public String getProducts()
    {
        return getStringProperty(ATTR_Products);
    }

    public void setProducts(String value)
    {
        setProperty(ATTR_Products, value, 0);
    }

    public String getCheckLists()
    {
        return getStringProperty(ATTR_CheckLists);
    }

    public void setCheckLists(String value)
    {
        setProperty(ATTR_CheckLists, value, 0);
    }

    public String getCompletedRequirementFlag()
    {
        return getStringProperty(ATTR_CompletedRequirementFlag);
    }

    public void setCompletedRequirementFlag(String value)
    {
        setProperty(ATTR_CompletedRequirementFlag, value, 0);
    }

    public int getRequirementCount()
    {
        return getIntProperty(ATTR_RequirementCount);
    }

    public void setRequirementCount(int value)
    {
        setProperty(ATTR_RequirementCount, value, 0);
    }

    public String getRequirementStatus()
    {
        return getStringProperty(ATTR_RequirementStatus);
    }

    public void setRequirementStatus(String value)
    {
        setProperty(ATTR_RequirementStatus, value, 0);
    }

    public String getMRSPKID()
    {
        return getStringProperty(ATTR_MRSPKID);
    }

    public void setMRSPKID(String value)
    {
        setProperty(ATTR_MRSPKID, value, 0);
    }



    public static BusObjectIterator<com.cica.uw.tbl_Worksite_VendorOrderRequirementTask> getNextTbl_Worksite_VendorOrderRequirementTaskObjects(long Tableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_Worksite_VendorOrderRequirementTask\" where (\"tableid\" > :Tableid) order by \"tableid\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(Tableid));//NOPMD
        query.setResultClass(tbl_Worksite_VendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_Worksite_VendorOrderRequirementTask> getPreviousTbl_Worksite_VendorOrderRequirementTaskObjects(long Tableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_Worksite_VendorOrderRequirementTask\" where (\"tableid\" < :Tableid) order by \"tableid\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(Tableid));//NOPMD
        query.setResultClass(tbl_Worksite_VendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tbl_Worksite_VendorOrderRequirementTask getTbl_Worksite_VendorOrderRequirementTaskObject(long Tableid)
    {
        String queryText = "select * from \"tbl_Worksite_VendorOrderRequirementTask\" where \"tableid\" = :Tableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Tableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(Tableid));//NOPMD
        query.setResultClass(tbl_Worksite_VendorOrderRequirementTask.class);
        return (tbl_Worksite_VendorOrderRequirementTask)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tbl_Worksite_VendorOrderRequirementTask> getTbl_Worksite_VendorOrderRequirementTaskObjects(long fromTableid, long toTableid, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tbl_Worksite_VendorOrderRequirementTask\" where \"tableid\" between :fromTableid and :toTableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromTableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(fromTableid));
        query.addParameter("toTableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(toTableid));
        query.setResultClass(tbl_Worksite_VendorOrderRequirementTask.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tbl_Worksite_VendorOrderRequirementTask> getTbl_Worksite_VendorOrderRequirementTaskObjects(long fromTableid, long toTableid)
    {
        String queryText = "select * from \"tbl_Worksite_VendorOrderRequirementTask\" where \"tableid\" between :fromTableid and :toTableid";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromTableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(fromTableid));
        query.addParameter("toTableid", "tbl_Worksite_VendorOrderRequirementTask.tableid", QueryObject.PARAM_INT, new Long(toTableid));
        query.setResultClass(tbl_Worksite_VendorOrderRequirementTask.class);
        return query.getObjects();
    }



}
