/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class tbl_underwriting_NonVendorOrderRequirementTask extends tbl_underwriting_NonVendorOrderRequirementTaskBase
{
    public tbl_underwriting_NonVendorOrderRequirementTask()
    {
        this((BusObjectConfig)null);
    }

    public tbl_underwriting_NonVendorOrderRequirementTask(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.tbl_underwriting_NonVendorOrderRequirementTask> GetTblUnderwritingNonVendorOrderRequirementTaskTableIDUsingReqid(long OrderRequirementReqID)
    {
			QueryObject query;			
			String queryText="SELECT * FROM tbl_underwriting_NonVendorOrderRequirementTask where req_id =  :OrderRequirementReqID";
			query=new QueryObject(queryText);
			query.addParameter("OrderRequirementReqID", "tbl_underwriting_NonVendorOrderRequirementTask .req_id ",QueryObject.PARAM_STRING, OrderRequirementReqID);
			query.setResultClass(tbl_underwriting_NonVendorOrderRequirementTask.class);
			return query.getObjects();

    }

}
