/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tbl_state_prov extends tbl_state_provBase
{
    public tbl_state_prov()
    {
        this((BusObjectConfig)null);
    }

    public tbl_state_prov(BusObjectConfig config)
    {
        super(config);
    }

}
