/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class tblMillimanDetails extends tblMillimanDetailsBase
{
    public tblMillimanDetails()
    {
        this((BusObjectConfig)null);
    }

    public tblMillimanDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.tblMillimanDetails> getMillimanDetailsOnTrackingID(String trackingID)
    {
        String queryText = "select * from tblMillimanDetails where TrackingID=:trackingID";
        QueryObject query = new QueryObject(queryText);
		query.addParameter("trackingID", "tblMillimanDetails.TrackingID", QueryObject.PARAM_STRING, trackingID);
        query.setResultClass(tblMillimanDetails.class);
        
        return query.getObjects();
    }

}
