/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class tblMRSSchema extends tblMRSSchemaBase
{
    public tblMRSSchema()
    {
        this((BusObjectConfig)null);
    }

    public tblMRSSchema(BusObjectConfig config)
    {
        super(config);
    }

}
