/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tblMillimanLifeCMDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_ID = "ID";
    public final static String ATTR_PolicyNumber = "PolicyNumber";
    public final static String ATTR_CMDocID = "CMDocID";
    public final static String ATTR_CreationDate = "CreationDate";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tblMillimanLifeCMDetails.class);
            s_classInfo.setTableName("tblMillimanLifeCMDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_PolicyNumber});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setColumnName(ATTR_ID);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PolicyNumber);
                ai.setJavaName(ATTR_PolicyNumber);
                ai.setColumnName(ATTR_PolicyNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PolicyNumber);
                v.setMaxLength(30);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CMDocID);
                ai.setJavaName(ATTR_CMDocID);
                ai.setColumnName(ATTR_CMDocID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CMDocID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreationDate);
                ai.setJavaName(ATTR_CreationDate);
                ai.setColumnName(ATTR_CreationDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tblMillimanLifeCMDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getID()
    {
        return getIntProperty(ATTR_ID);
    }

    public void setID(int value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getPolicyNumber()
    {
        return getStringProperty(ATTR_PolicyNumber);
    }

    public void setPolicyNumber(String value)
    {
        setProperty(ATTR_PolicyNumber, value, 0);
    }

    public String getCMDocID()
    {
        return getStringProperty(ATTR_CMDocID);
    }

    public void setCMDocID(String value)
    {
        setProperty(ATTR_CMDocID, value, 0);
    }

    public java.util.Date getCreationDate()
    {
        return getDateTimestampProperty(ATTR_CreationDate);
    }

    public void setCreationDate(java.util.Date value)
    {
        setProperty(ATTR_CreationDate, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.tblMillimanLifeCMDetails> getNextTblMillimanLifeCMDetailsObjects(String PolicyNumber, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblMillimanLifeCMDetails\" where (\"PolicyNumber\" > :PolicyNumber) order by \"PolicyNumber\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, PolicyNumber);//NOPMD
        query.setResultClass(tblMillimanLifeCMDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblMillimanLifeCMDetails> getPreviousTblMillimanLifeCMDetailsObjects(String PolicyNumber, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblMillimanLifeCMDetails\" where (\"PolicyNumber\" < :PolicyNumber) order by \"PolicyNumber\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, PolicyNumber);//NOPMD
        query.setResultClass(tblMillimanLifeCMDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tblMillimanLifeCMDetails getTblMillimanLifeCMDetailsObject(String PolicyNumber)
    {
        String queryText = "select * from \"tblMillimanLifeCMDetails\" where \"PolicyNumber\" = :PolicyNumber";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, PolicyNumber);//NOPMD
        query.setResultClass(tblMillimanLifeCMDetails.class);
        return (tblMillimanLifeCMDetails)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tblMillimanLifeCMDetails> getTblMillimanLifeCMDetailsObjects(String fromPolicyNumber, String toPolicyNumber, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblMillimanLifeCMDetails\" where \"PolicyNumber\" between :fromPolicyNumber and :toPolicyNumber";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, fromPolicyNumber);
        query.addParameter("toPolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, toPolicyNumber);
        query.setResultClass(tblMillimanLifeCMDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblMillimanLifeCMDetails> getTblMillimanLifeCMDetailsObjects(String fromPolicyNumber, String toPolicyNumber)
    {
        String queryText = "select * from \"tblMillimanLifeCMDetails\" where \"PolicyNumber\" between :fromPolicyNumber and :toPolicyNumber";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, fromPolicyNumber);
        query.addParameter("toPolicyNumber", "tblMillimanLifeCMDetails.PolicyNumber", QueryObject.PARAM_STRING, toPolicyNumber);
        query.setResultClass(tblMillimanLifeCMDetails.class);
        return query.getObjects();
    }

}
