/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tblUWPI_TaskDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_PITaskId = "PITaskId";
    public final static String ATTR_TaskInstanceId = "TaskInstanceId";
    public final static String ATTR_TaskName = "TaskName";
    public final static String ATTR_PolicyNumber = "PolicyNumber";
    public final static String ATTR_GroupNumber = "GroupNumber";
    public final static String ATTR_GroupName = "GroupName";
    public final static String ATTR_Lob = "Lob";
    public final static String ATTR_ServiceType = "ServiceType";
    public final static String ATTR_InsuredName = "InsuredName";
    public final static String ATTR_Province = "Province";
    public final static String ATTR_Language = "Language";
    public final static String ATTR_Source = "Source";
    public final static String ATTR_TaskStatus = "TaskStatus";
    public final static String ATTR_AssignName = "AssignName";
    public final static String ATTR_Reason = "Reason";
    public final static String ATTR_DueDate = "DueDate";
    public final static String ATTR_ReqType = "ReqType";
    public final static String ATTR_ReqNotes = "ReqNotes";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_PICaseId = "PICaseId";
    public final static String ATTR_linkedTask = "linkedTask";
    public final static String ATTR_linkedTaskId = "linkedTaskId";
    public final static String ATTR_CancellationReason = "CancellationReason";
    public final static String ATTR_CancellationCode = "CancellationCode";
    public final static String ATTR_RequesterDN = "RequesterDN";
    public final static String ATTR_ParentTaskType = "ParentTaskType";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_UpdatedDate = "UpdatedDate";
    public final static String ATTR_FollowUpAction = "FollowUpAction";
    public final static String ATTR_FollowUpDate = "FollowUpDate";
    public final static String ATTR_Decision = "Decision";
    public final static String ATTR_Product = "Product";
    public final static String ATTR_CM8_Docid = "CM8_Docid";
    public final static String ATTR_Index_class = "Index_class";
    public final static String ATTR_CustomerID = "CustomerID";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tblUWPI_TaskDetails.class);
            s_classInfo.setTableName("tblUWPI_TaskDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_PITaskId});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PITaskId);
                ai.setJavaName(ATTR_PITaskId);
                ai.setColumnName(ATTR_PITaskId);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_PITaskId);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskInstanceId);
                ai.setJavaName(ATTR_TaskInstanceId);
                ai.setColumnName(ATTR_TaskInstanceId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskInstanceId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskName);
                ai.setJavaName(ATTR_TaskName);
                ai.setColumnName(ATTR_TaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskName);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PolicyNumber);
                ai.setJavaName(ATTR_PolicyNumber);
                ai.setColumnName(ATTR_PolicyNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PolicyNumber);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GroupNumber);
                ai.setJavaName(ATTR_GroupNumber);
                ai.setColumnName(ATTR_GroupNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GroupNumber);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GroupName);
                ai.setJavaName(ATTR_GroupName);
                ai.setColumnName(ATTR_GroupName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GroupName);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Lob);
                ai.setJavaName(ATTR_Lob);
                ai.setColumnName(ATTR_Lob);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Lob);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ServiceType);
                ai.setJavaName(ATTR_ServiceType);
                ai.setColumnName(ATTR_ServiceType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ServiceType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_InsuredName);
                ai.setJavaName(ATTR_InsuredName);
                ai.setColumnName(ATTR_InsuredName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_InsuredName);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Province);
                ai.setJavaName(ATTR_Province);
                ai.setColumnName(ATTR_Province);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Province);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Language);
                ai.setJavaName(ATTR_Language);
                ai.setColumnName(ATTR_Language);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Language);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Source);
                ai.setJavaName(ATTR_Source);
                ai.setColumnName(ATTR_Source);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Source);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskStatus);
                ai.setJavaName(ATTR_TaskStatus);
                ai.setColumnName(ATTR_TaskStatus);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskStatus);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AssignName);
                ai.setJavaName(ATTR_AssignName);
                ai.setColumnName(ATTR_AssignName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AssignName);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Reason);
                ai.setJavaName(ATTR_Reason);
                ai.setColumnName(ATTR_Reason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Reason);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DueDate);
                ai.setJavaName(ATTR_DueDate);
                ai.setColumnName(ATTR_DueDate);
                ai.setAttributeClass(java.sql.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReqType);
                ai.setJavaName(ATTR_ReqType);
                ai.setColumnName(ATTR_ReqType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ReqType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReqNotes);
                ai.setJavaName(ATTR_ReqNotes);
                ai.setColumnName(ATTR_ReqNotes);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ReqNotes);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(150);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PICaseId);
                ai.setJavaName(ATTR_PICaseId);
                ai.setColumnName(ATTR_PICaseId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PICaseId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_linkedTask);
                ai.setJavaName(ATTR_linkedTask);
                ai.setColumnName(ATTR_linkedTask);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_linkedTask);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_linkedTaskId);
                ai.setJavaName(ATTR_linkedTaskId);
                ai.setColumnName(ATTR_linkedTaskId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_linkedTaskId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationReason);
                ai.setJavaName(ATTR_CancellationReason);
                ai.setColumnName(ATTR_CancellationReason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationReason);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationCode);
                ai.setJavaName(ATTR_CancellationCode);
                ai.setColumnName(ATTR_CancellationCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationCode);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequesterDN);
                ai.setJavaName(ATTR_RequesterDN);
                ai.setColumnName(ATTR_RequesterDN);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequesterDN);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ParentTaskType);
                ai.setJavaName(ATTR_ParentTaskType);
                ai.setColumnName(ATTR_ParentTaskType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ParentTaskType);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedDate);
                ai.setJavaName(ATTR_UpdatedDate);
                ai.setColumnName(ATTR_UpdatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpAction);
                ai.setJavaName(ATTR_FollowUpAction);
                ai.setColumnName(ATTR_FollowUpAction);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FollowUpAction);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpDate);
                ai.setJavaName(ATTR_FollowUpDate);
                ai.setColumnName(ATTR_FollowUpDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Decision);
                ai.setJavaName(ATTR_Decision);
                ai.setColumnName(ATTR_Decision);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Decision);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Product);
                ai.setJavaName(ATTR_Product);
                ai.setColumnName(ATTR_Product);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Product);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CM8_Docid);
                ai.setJavaName(ATTR_CM8_Docid);
                ai.setColumnName(ATTR_CM8_Docid);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CM8_Docid);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Index_class);
                ai.setJavaName(ATTR_Index_class);
                ai.setColumnName(ATTR_Index_class);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Index_class);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CustomerID);
                ai.setJavaName(ATTR_CustomerID);
                ai.setColumnName(ATTR_CustomerID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CustomerID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tblUWPI_TaskDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getPITaskId()
    {
        return getLongProperty(ATTR_PITaskId);
    }

    public void setPITaskId(long value)
    {
        setProperty(ATTR_PITaskId, value, 0);
    }

    public String getTaskInstanceId()
    {
        return getStringProperty(ATTR_TaskInstanceId);
    }

    public void setTaskInstanceId(String value)
    {
        setProperty(ATTR_TaskInstanceId, value, 0);
    }

    public String getTaskName()
    {
        return getStringProperty(ATTR_TaskName);
    }

    public void setTaskName(String value)
    {
        setProperty(ATTR_TaskName, value, 0);
    }

    public String getPolicyNumber()
    {
        return getStringProperty(ATTR_PolicyNumber);
    }

    public void setPolicyNumber(String value)
    {
        setProperty(ATTR_PolicyNumber, value, 0);
    }

    public String getGroupNumber()
    {
        return getStringProperty(ATTR_GroupNumber);
    }

    public void setGroupNumber(String value)
    {
        setProperty(ATTR_GroupNumber, value, 0);
    }

    public String getGroupName()
    {
        return getStringProperty(ATTR_GroupName);
    }

    public void setGroupName(String value)
    {
        setProperty(ATTR_GroupName, value, 0);
    }

    public String getLob()
    {
        return getStringProperty(ATTR_Lob);
    }

    public void setLob(String value)
    {
        setProperty(ATTR_Lob, value, 0);
    }

    public String getServiceType()
    {
        return getStringProperty(ATTR_ServiceType);
    }

    public void setServiceType(String value)
    {
        setProperty(ATTR_ServiceType, value, 0);
    }

    public String getInsuredName()
    {
        return getStringProperty(ATTR_InsuredName);
    }

    public void setInsuredName(String value)
    {
        setProperty(ATTR_InsuredName, value, 0);
    }

    public String getProvince()
    {
        return getStringProperty(ATTR_Province);
    }

    public void setProvince(String value)
    {
        setProperty(ATTR_Province, value, 0);
    }

    public String getLanguage()
    {
        return getStringProperty(ATTR_Language);
    }

    public void setLanguage(String value)
    {
        setProperty(ATTR_Language, value, 0);
    }

    public String getSource()
    {
        return getStringProperty(ATTR_Source);
    }

    public void setSource(String value)
    {
        setProperty(ATTR_Source, value, 0);
    }

    public String getTaskStatus()
    {
        return getStringProperty(ATTR_TaskStatus);
    }

    public void setTaskStatus(String value)
    {
        setProperty(ATTR_TaskStatus, value, 0);
    }

    public String getAssignName()
    {
        return getStringProperty(ATTR_AssignName);
    }

    public void setAssignName(String value)
    {
        setProperty(ATTR_AssignName, value, 0);
    }

    public String getReason()
    {
        return getStringProperty(ATTR_Reason);
    }

    public void setReason(String value)
    {
        setProperty(ATTR_Reason, value, 0);
    }

    public java.sql.Date getDueDate()
    {
        return getSqlDateProperty(ATTR_DueDate);
    }

    public void setDueDate(java.sql.Date value)
    {
        setProperty(ATTR_DueDate, value, 0);
    }

    public String getReqType()
    {
        return getStringProperty(ATTR_ReqType);
    }

    public void setReqType(String value)
    {
        setProperty(ATTR_ReqType, value, 0);
    }

    public String getReqNotes()
    {
        return getStringProperty(ATTR_ReqNotes);
    }

    public void setReqNotes(String value)
    {
        setProperty(ATTR_ReqNotes, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public java.util.Date getCreatedDate()
    {
        return getDateTimestampProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.util.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getPICaseId()
    {
        return getStringProperty(ATTR_PICaseId);
    }

    public void setPICaseId(String value)
    {
        setProperty(ATTR_PICaseId, value, 0);
    }

    public String getLinkedTask()
    {
        return getStringProperty(ATTR_linkedTask);
    }

    public void setLinkedTask(String value)
    {
        setProperty(ATTR_linkedTask, value, 0);
    }

    public String getLinkedTaskId()
    {
        return getStringProperty(ATTR_linkedTaskId);
    }

    public void setLinkedTaskId(String value)
    {
        setProperty(ATTR_linkedTaskId, value, 0);
    }

    public String getCancellationReason()
    {
        return getStringProperty(ATTR_CancellationReason);
    }

    public void setCancellationReason(String value)
    {
        setProperty(ATTR_CancellationReason, value, 0);
    }

    public String getCancellationCode()
    {
        return getStringProperty(ATTR_CancellationCode);
    }

    public void setCancellationCode(String value)
    {
        setProperty(ATTR_CancellationCode, value, 0);
    }

    public String getRequesterDN()
    {
        return getStringProperty(ATTR_RequesterDN);
    }

    public void setRequesterDN(String value)
    {
        setProperty(ATTR_RequesterDN, value, 0);
    }

    public String getParentTaskType()
    {
        return getStringProperty(ATTR_ParentTaskType);
    }

    public void setParentTaskType(String value)
    {
        setProperty(ATTR_ParentTaskType, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getUpdatedDate()
    {
        return getDateTimestampProperty(ATTR_UpdatedDate);
    }

    public void setUpdatedDate(java.util.Date value)
    {
        setProperty(ATTR_UpdatedDate, value, 0);
    }

    public String getFollowUpAction()
    {
        return getStringProperty(ATTR_FollowUpAction);
    }

    public void setFollowUpAction(String value)
    {
        setProperty(ATTR_FollowUpAction, value, 0);
    }

    public java.util.Date getFollowUpDate()
    {
        return getDateTimestampProperty(ATTR_FollowUpDate);
    }

    public void setFollowUpDate(java.util.Date value)
    {
        setProperty(ATTR_FollowUpDate, value, 0);
    }

    public String getDecision()
    {
        return getStringProperty(ATTR_Decision);
    }

    public void setDecision(String value)
    {
        setProperty(ATTR_Decision, value, 0);
    }

    public String getProduct()
    {
        return getStringProperty(ATTR_Product);
    }

    public void setProduct(String value)
    {
        setProperty(ATTR_Product, value, 0);
    }

    public String getCM8_Docid()
    {
        return getStringProperty(ATTR_CM8_Docid);
    }

    public void setCM8_Docid(String value)
    {
        setProperty(ATTR_CM8_Docid, value, 0);
    }

    public String getIndex_class()
    {
        return getStringProperty(ATTR_Index_class);
    }

    public void setIndex_class(String value)
    {
        setProperty(ATTR_Index_class, value, 0);
    }

    public String getCustomerID()
    {
        return getStringProperty(ATTR_CustomerID);
    }

    public void setCustomerID(String value)
    {
        setProperty(ATTR_CustomerID, value, 0);
    }



    public static BusObjectIterator<com.cica.uw.tblUWPI_TaskDetails> getNextTblUWPI_TaskDetailsObjects(long PITaskId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_TaskDetails\" where (\"PITaskId\" > :PITaskId) order by \"PITaskId\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(PITaskId));//NOPMD
        query.setResultClass(tblUWPI_TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_TaskDetails> getPreviousTblUWPI_TaskDetailsObjects(long PITaskId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_TaskDetails\" where (\"PITaskId\" < :PITaskId) order by \"PITaskId\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(PITaskId));//NOPMD
        query.setResultClass(tblUWPI_TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tblUWPI_TaskDetails getTblUWPI_TaskDetailsObject(long PITaskId)
    {
        String queryText = "select * from \"tblUWPI_TaskDetails\" where \"PITaskId\" = :PITaskId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(PITaskId));//NOPMD
        query.setResultClass(tblUWPI_TaskDetails.class);
        return (tblUWPI_TaskDetails)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_TaskDetails> getTblUWPI_TaskDetailsObjects(long fromPITaskId, long toPITaskId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_TaskDetails\" where \"PITaskId\" between :fromPITaskId and :toPITaskId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(fromPITaskId));
        query.addParameter("toPITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(toPITaskId));
        query.setResultClass(tblUWPI_TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_TaskDetails> getTblUWPI_TaskDetailsObjects(long fromPITaskId, long toPITaskId)
    {
        String queryText = "select * from \"tblUWPI_TaskDetails\" where \"PITaskId\" between :fromPITaskId and :toPITaskId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromPITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(fromPITaskId));
        query.addParameter("toPITaskId", "tblUWPI_TaskDetails.PITaskId", QueryObject.PARAM_INT, new Long(toPITaskId));
        query.setResultClass(tblUWPI_TaskDetails.class);
        return query.getObjects();
    }

}
