/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.busobject.DMLStatement;
import com.cordys.cpc.bsf.busobject.BSF;
import java.util.Calendar;
import java.text.DateFormat;


public class tblUWPI_TaskDetails extends tblUWPI_TaskDetailsBase
{
    public tblUWPI_TaskDetails()
    {
        this((BusObjectConfig)null);
    }

    public tblUWPI_TaskDetails(BusObjectConfig config)
    {
        super(config);
    }

@Override
    protected void onBeforeInsert() {
    	String userDN=BSF.getUser();
    	this.setCreatedBy(userDN.substring((userDN.indexOf("="))+1, userDN.indexOf(",")));    	
    	this.setCreatedDate(new Date());    	
    }
    @Override
    protected void onBeforeUpdate() {
    	String userDN=BSF.getUser();
    	this.setUpdatedBy(userDN.substring((userDN.indexOf("="))+1, userDN.indexOf(",")));
    	this.setUpdatedDate(new Date());    	
    }

    public static com.cica.uw.tblUWPI_TaskDetails GetdatabyTaskDetails(String TaskInstanceId)
    {
         String queryText="select * from tblUWPI_TaskDetails  where TaskInstanceId = :TaskInstanceId"; 

	QueryObject querytblUWPI_TaskDetails = new QueryObject(queryText);
                querytblUWPI_TaskDetails.addParameter("TaskInstanceId", "tblUWPI_TaskDetails.TaskInstanceId", QueryObject.PARAM_STRING, TaskInstanceId);
                querytblUWPI_TaskDetails.setResultClass(tblUWPI_TaskDetails.class);
                return (tblUWPI_TaskDetails )querytblUWPI_TaskDetails.getObject();
    }

    public static com.cica.uw.tblUWPI_TaskDetails getActiveTaskFromTaskDetail(String OTCaseID, String TaskName )
    {
         String queryText="select * from tblUWPI_TaskDetails  where PICaseID = '"+OTCaseID+"' and TaskName='"+TaskName+"'"; 

	QueryObject querytblUWPI_TaskDetails = new QueryObject(queryText);
               // querytblUWPI_TaskDetails.addParameter("TaskInstanceId", "tblUWPI_TaskDetails.TaskInstanceId", QueryObject.PARAM_STRING, TaskInstanceId);
                querytblUWPI_TaskDetails.setResultClass(tblUWPI_TaskDetails.class);
                return (tblUWPI_TaskDetails )querytblUWPI_TaskDetails.getObject();
    }

}
