/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.QueryObject;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


public class tblUWPI_DropdownData extends tblUWPI_DropdownDataBase
{
    public tblUWPI_DropdownData()
    {
        this((BusObjectConfig)null);
    }

    public tblUWPI_DropdownData(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_DropdownData> tblUWPI_DropdownDataOnIdentifier(String Identifier)
  {
        
String queryText = "select Description,Value from tblUWPI_DropdownData where Identifier=:data order by SrNO";
QueryObject query = new QueryObject(queryText);
query.addParameter("data", "tblUWPI_DropdownData.Identifier", QueryObject.PARAM_STRING, Identifier);//NOPMD
query.setResultClass(tblUWPI_DropdownData .class);

return query.getObjects(); //To fetch Multiple records
    }

}
