/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;



public class tblUWPI_FollowUp1 extends tblUWPI_FollowUp1Base
{
    public tblUWPI_FollowUp1()
    {
        this((BusObjectConfig)null);
    }

    public tblUWPI_FollowUp1(BusObjectConfig config)
    {
        super(config);
    }

    public static com.cica.uw.tblUWPI_FollowUp1 GetFollowUpByPolicyNoandTaskID(String PolicyNumber, String TaskInstanceID)
    {
       String queryText = "select * from \"tblUWPI_FollowUp1 \" where \"PolicyNumber\"=:PolicyNumber and \"TaskInstanceID\"=:TaskInstanceID ";
        QueryObject query = new QueryObject(queryText);
        query. addParameter("PolicyNumber", "tblUWPI_FollowUp1 .PolicyNumber", QueryObject.PARAM_STRING, PolicyNumber);
    query. addParameter("TaskInstanceID", "tblUWPI_FollowUp1 .TaskInstanceID", QueryObject.PARAM_STRING, TaskInstanceID);   //NOPMD
        query.setResultClass(tblUWPI_FollowUp1 .class);
        return (tblUWPI_FollowUp1 )query.getObject(); //To fetch single record
	//return query.getObjects();  //To fetch Multiple records


    }

}
