/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class tblUWPI_DropdownDataBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SrNo = "SrNo";
    public final static String ATTR_Identifier = "Identifier";
    public final static String ATTR_Description = "Description";
    public final static String ATTR_Value = "Value";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_UpdatedDate = "UpdatedDate";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(tblUWPI_DropdownData.class);
            s_classInfo.setTableName("tblUWPI_DropdownData");
            s_classInfo.setUIDElements(new String[]{ATTR_SrNo});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SrNo);
                ai.setJavaName(ATTR_SrNo);
                ai.setColumnName(ATTR_SrNo);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_SrNo);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Identifier);
                ai.setJavaName(ATTR_Identifier);
                ai.setColumnName(ATTR_Identifier);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Identifier);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setColumnName(ATTR_Description);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Description);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Value);
                ai.setJavaName(ATTR_Value);
                ai.setColumnName(ATTR_Value);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Value);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedDate);
                ai.setJavaName(ATTR_UpdatedDate);
                ai.setColumnName(ATTR_UpdatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public tblUWPI_DropdownDataBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getSrNo()
    {
        return getLongProperty(ATTR_SrNo);
    }

    public void setSrNo(long value)
    {
        setProperty(ATTR_SrNo, value, 0);
    }

    public String getIdentifier()
    {
        return getStringProperty(ATTR_Identifier);
    }

    public void setIdentifier(String value)
    {
        setProperty(ATTR_Identifier, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }

    public String getValue()
    {
        return getStringProperty(ATTR_Value);
    }

    public void setValue(String value)
    {
        setProperty(ATTR_Value, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public java.util.Date getCreatedDate()
    {
        return getDateTimestampProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.util.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getUpdatedDate()
    {
        return getDateTimestampProperty(ATTR_UpdatedDate);
    }

    public void setUpdatedDate(java.util.Date value)
    {
        setProperty(ATTR_UpdatedDate, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_DropdownData> getNextTblUWPI_DropdownDataObjects(long SrNo, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_DropdownData\" where (\"SrNo\" > :SrNo) order by \"SrNo\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(SrNo));//NOPMD
        query.setResultClass(tblUWPI_DropdownData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_DropdownData> getPreviousTblUWPI_DropdownDataObjects(long SrNo, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_DropdownData\" where (\"SrNo\" < :SrNo) order by \"SrNo\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(SrNo));//NOPMD
        query.setResultClass(tblUWPI_DropdownData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.tblUWPI_DropdownData getTblUWPI_DropdownDataObject(long SrNo)
    {
        String queryText = "select * from \"tblUWPI_DropdownData\" where \"SrNo\" = :SrNo";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(SrNo));//NOPMD
        query.setResultClass(tblUWPI_DropdownData.class);
        return (tblUWPI_DropdownData)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_DropdownData> getTblUWPI_DropdownDataObjects(long fromSrNo, long toSrNo, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"tblUWPI_DropdownData\" where \"SrNo\" between :fromSrNo and :toSrNo";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(fromSrNo));
        query.addParameter("toSrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(toSrNo));
        query.setResultClass(tblUWPI_DropdownData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_DropdownData> getTblUWPI_DropdownDataObjects(long fromSrNo, long toSrNo)
    {
        String queryText = "select * from \"tblUWPI_DropdownData\" where \"SrNo\" between :fromSrNo and :toSrNo";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(fromSrNo));
        query.addParameter("toSrNo", "tblUWPI_DropdownData.SrNo", QueryObject.PARAM_INT, new Long(toSrNo));
        query.setResultClass(tblUWPI_DropdownData.class);
        return query.getObjects();
    }


}
