/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;


import com.cordys.cpc.bsf.busobject.BusObjectConfig;import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.logger.CordysLogger;
import com.eibus.util.logger.Severity;


public class tblUWPI_PostIssueDetails extends tblUWPI_PostIssueDetailsBase
{
    public tblUWPI_PostIssueDetails()
    {
        this((BusObjectConfig)null);
    }

    public tblUWPI_PostIssueDetails(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.cica.uw.tblUWPI_PostIssueDetails> GetUnprocessedUWPostIssueDetails()
    {
      String queryText = "select  * from tblUWPI_PostIssueDetails  where PICaseId is null";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tblUWPI_PostIssueDetails  .class);
        return query.getObjects();
    }

    public static com.cica.uw.tblUWPI_PostIssueDetails Getpostdetailsbypolicynumber(String PolicyNumber)
    {
       String queryText = "select *  from tblUWPI_PostIssueDetails  where PolicyNumber = :PolicyNumber";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PolicyNumber", "tblUWPI_PostIssueDetails .PolicyNumber", QueryObject.PARAM_STRING, PolicyNumber);//NOPMD
        query.setResultClass(tblUWPI_PostIssueDetails.class);
        return (tblUWPI_PostIssueDetails)query.getObject();
    }

    public static com.cica.uw.tblUWPI_PostIssueDetails Getpostissuedeatailsbycaseid(String PICaseId)
    {
     String queryText = "select *  from tblUWPI_PostIssueDetails  where PICaseId= :PICaseId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PICaseId", "tblUWPI_PostIssueDetails.PICaseId", QueryObject.PARAM_STRING, PICaseId);//NOPMD
        query.setResultClass(tblUWPI_PostIssueDetails.class);
        return (tblUWPI_PostIssueDetails)query.getObject();
    }
	
    public static BusObjectIterator<com.cica.uw.tblUWPI_PostIssueDetails> GetUnprocessedUWPIDetails()
    {
                String queryText = "select  * from tblUWPI_PostIssueDetails where CaseId is null or CaseId='' ";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tblUWPI_PostIssueDetails.class);
        return query.getObjects();
    }

  public static BusObjectIterator<com.cica.uw.tblUWPI_PostIssueDetails> getRecordForJetIssue( String CaseID)
    {
                String queryText = "select  * from tblUWPI_PostIssueDetails where CaseId ='"+CaseID+"'";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(tblUWPI_PostIssueDetails.class);
        return query.getObjects();
    }
public static  BusObjectIterator<com.cica.uw.tblUWPI_PostIssueDetails>  GetCaseInPendingWorkList()
{
   String queryText = "select CaseId,PICaseId from tblUWPI_PostIssueDetails where PICaseId in \r\n" + 
   		"(select Dependent_SNO from \r\n" + 
   		"UWManualTaskDetails where Dependent_SNO in\r\n" + 
   		"(select PICaseId from tblUWPI_PostIssueDetails where CaseStatus='In Pending Worklist') and Status='Completed')";
   QueryObject query = new QueryObject(queryText);
   query.setResultClass(tblUWPI_PostIssueDetails.class);
   return query.getObjects();
}
 public static String getCM8DocIDonCaseID(String PICaseId)
    {
       String queryText = "select SUBSTRING(CM8_Docid, CHARINDEX('26',CM8_Docid)+3,26) as cm8id from tblUWPI_PostIssueDetails where PICaseId=:PICaseId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PICaseId", "tblUWPI_PostIssueDetails .PICaseId", QueryObject.PARAM_STRING, PICaseId);//NOPMD
        query.setResultClass(tblUWPI_PostIssueDetails.class);
        return query.getObject().getStringProperty("cm8id");
    }

}
