/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class TIMERBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_TASK_ID = "TASK_ID";
    public final static String ATTR_SESSION_ID = "SESSION_ID";
    public final static String ATTR_ACTION = "ACTION";
    public final static String ATTR_USER_ID = "USER_ID";
    public final static String ATTR_TASK_NAME = "TASK_NAME";
    public final static String ATTR_PROCESS_NAME = "PROCESS_NAME";
    public final static String ATTR_START_TIME = "START_TIME";
    public final static String ATTR_END_TIME = "END_TIME";
    public final static String ATTR_CASE_INST_ID = "CASE_INST_ID";
    public final static String ATTR_ASSIGNEE = "ASSIGNEE";
    public final static String ATTR_WINDOW_ID = "WINDOW_ID";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(TIMER.class);
            s_classInfo.setTableName("TIMER");
            s_classInfo.setUIDElements(new String[]{ATTR_SESSION_ID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TASK_ID);
                ai.setJavaName(ATTR_TASK_ID);
                ai.setColumnName(ATTR_TASK_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TASK_ID);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SESSION_ID);
                ai.setJavaName(ATTR_SESSION_ID);
                ai.setColumnName(ATTR_SESSION_ID);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_SESSION_ID);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ACTION);
                ai.setJavaName(ATTR_ACTION);
                ai.setColumnName(ATTR_ACTION);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ACTION);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_USER_ID);
                ai.setJavaName(ATTR_USER_ID);
                ai.setColumnName(ATTR_USER_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_USER_ID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TASK_NAME);
                ai.setJavaName(ATTR_TASK_NAME);
                ai.setColumnName(ATTR_TASK_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TASK_NAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PROCESS_NAME);
                ai.setJavaName(ATTR_PROCESS_NAME);
                ai.setColumnName(ATTR_PROCESS_NAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PROCESS_NAME);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_START_TIME);
                ai.setJavaName(ATTR_START_TIME);
                ai.setColumnName(ATTR_START_TIME);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_END_TIME);
                ai.setJavaName(ATTR_END_TIME);
                ai.setColumnName(ATTR_END_TIME);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CASE_INST_ID);
                ai.setJavaName(ATTR_CASE_INST_ID);
                ai.setColumnName(ATTR_CASE_INST_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CASE_INST_ID);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ASSIGNEE);
                ai.setJavaName(ATTR_ASSIGNEE);
                ai.setColumnName(ATTR_ASSIGNEE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ASSIGNEE);
                v.setMaxLength(1);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_WINDOW_ID);
                ai.setJavaName(ATTR_WINDOW_ID);
                ai.setColumnName(ATTR_WINDOW_ID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_WINDOW_ID);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public TIMERBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getTASK_ID()
    {
        return getStringProperty(ATTR_TASK_ID);
    }

    public void setTASK_ID(String value)
    {
        setProperty(ATTR_TASK_ID, value, 0);
    }

    public long getSESSION_ID()
    {
        return getLongProperty(ATTR_SESSION_ID);
    }

    public void setSESSION_ID(long value)
    {
        setProperty(ATTR_SESSION_ID, value, 0);
    }

    public String getACTION()
    {
        return getStringProperty(ATTR_ACTION);
    }

    public void setACTION(String value)
    {
        setProperty(ATTR_ACTION, value, 0);
    }

    public String getUSER_ID()
    {
        return getStringProperty(ATTR_USER_ID);
    }

    public void setUSER_ID(String value)
    {
        setProperty(ATTR_USER_ID, value, 0);
    }

    public String getTASK_NAME()
    {
        return getStringProperty(ATTR_TASK_NAME);
    }

    public void setTASK_NAME(String value)
    {
        setProperty(ATTR_TASK_NAME, value, 0);
    }

    public String getPROCESS_NAME()
    {
        return getStringProperty(ATTR_PROCESS_NAME);
    }

    public void setPROCESS_NAME(String value)
    {
        setProperty(ATTR_PROCESS_NAME, value, 0);
    }

    public java.util.Date getSTART_TIME()
    {
        return getDateTimestampProperty(ATTR_START_TIME);
    }

    public void setSTART_TIME(java.util.Date value)
    {
        setProperty(ATTR_START_TIME, value, 0);
    }

    public java.util.Date getEND_TIME()
    {
        return getDateTimestampProperty(ATTR_END_TIME);
    }

    public void setEND_TIME(java.util.Date value)
    {
        setProperty(ATTR_END_TIME, value, 0);
    }

    public String getCASE_INST_ID()
    {
        return getStringProperty(ATTR_CASE_INST_ID);
    }

    public void setCASE_INST_ID(String value)
    {
        setProperty(ATTR_CASE_INST_ID, value, 0);
    }

    public String getASSIGNEE()
    {
        return getStringProperty(ATTR_ASSIGNEE);
    }

    public void setASSIGNEE(String value)
    {
        setProperty(ATTR_ASSIGNEE, value, 0);
    }

    public String getWINDOW_ID()
    {
        return getStringProperty(ATTR_WINDOW_ID);
    }

    public void setWINDOW_ID(String value)
    {
        setProperty(ATTR_WINDOW_ID, value, 0);
    }

    public static BusObjectIterator<com.cica.uw.TIMER> getNextTimerObjects(long SESSION_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TIMER\" where (\"SESSION_ID\" > :SESSION_ID) order by \"SESSION_ID\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(SESSION_ID));//NOPMD
        query.setResultClass(TIMER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.TIMER> getPreviousTimerObjects(long SESSION_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TIMER\" where (\"SESSION_ID\" < :SESSION_ID) order by \"SESSION_ID\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(SESSION_ID));//NOPMD
        query.setResultClass(TIMER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.TIMER getTimerObject(long SESSION_ID)
    {
        String queryText = "select * from \"TIMER\" where \"SESSION_ID\" = :SESSION_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(SESSION_ID));//NOPMD
        query.setResultClass(TIMER.class);
        return (TIMER)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.TIMER> getTimerObjects(long fromSESSION_ID, long toSESSION_ID, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TIMER\" where \"SESSION_ID\" between :fromSESSION_ID and :toSESSION_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(fromSESSION_ID));
        query.addParameter("toSESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(toSESSION_ID));
        query.setResultClass(TIMER.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.TIMER> getTimerObjects(long fromSESSION_ID, long toSESSION_ID)
    {
        String queryText = "select * from \"TIMER\" where \"SESSION_ID\" between :fromSESSION_ID and :toSESSION_ID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(fromSESSION_ID));
        query.addParameter("toSESSION_ID", "TIMER.SESSION_ID", QueryObject.PARAM_INT, new Long(toSESSION_ID));
        query.setResultClass(TIMER.class);
        return query.getObjects();
    }

}
