/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class UW_EDMDataBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_Id = "Id";
    public final static String ATTR_UWReference = "UWReference";
    public final static String ATTR_Policy_Number = "Policy_Number";
    public final static String ATTR_Name = "Name";
    public final static String ATTR_State = "State";
    public final static String ATTR_Delivery_Method = "Delivery_Method";
    public final static String ATTR_ScanDate = "ScanDate";
    public final static String ATTR_PICS_CoverageCode = "PICS_CoverageCode";
    public final static String ATTR_Claim_ReasonCode = "Claim_ReasonCode";
    public final static String ATTR_TaskId = "TaskId";
    public final static String ATTR_Review_Claim_Decision = "Review_Claim_Decision";
    public final static String ATTR_ClaimNumber = "ClaimNumber";
    public final static String ATTR_CM_Docid = "CM_Docid";
    public final static String ATTR_LoadDate = "LoadDate";
    public final static String ATTR_WorkbasketName = "WorkbasketName";
    public final static String ATTR_CM8_Docid = "CM8_Docid";
    public final static String ATTR_IndexClass = "IndexClass";
    public final static String ATTR_DocumentType = "DocumentType";
    public final static String ATTR_Department = "Department";
    public final static String ATTR_PERID = "PERID";
    public final static String ATTR_DocDesc = "DocDesc";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UW_EDMData.class);
            s_classInfo.setTableName("UW_EDMData");
            s_classInfo.setUIDElements(new String[]{ATTR_Id});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Id);
                ai.setJavaName(ATTR_Id);
                ai.setColumnName(ATTR_Id);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_Id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UWReference);
                ai.setJavaName(ATTR_UWReference);
                ai.setColumnName(ATTR_UWReference);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UWReference);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Policy_Number);
                ai.setJavaName(ATTR_Policy_Number);
                ai.setColumnName(ATTR_Policy_Number);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Policy_Number);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Name);
                ai.setJavaName(ATTR_Name);
                ai.setColumnName(ATTR_Name);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Name);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_State);
                ai.setJavaName(ATTR_State);
                ai.setColumnName(ATTR_State);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_State);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Delivery_Method);
                ai.setJavaName(ATTR_Delivery_Method);
                ai.setColumnName(ATTR_Delivery_Method);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Delivery_Method);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ScanDate);
                ai.setJavaName(ATTR_ScanDate);
                ai.setColumnName(ATTR_ScanDate);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ScanDate);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PICS_CoverageCode);
                ai.setJavaName(ATTR_PICS_CoverageCode);
                ai.setColumnName(ATTR_PICS_CoverageCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PICS_CoverageCode);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Claim_ReasonCode);
                ai.setJavaName(ATTR_Claim_ReasonCode);
                ai.setColumnName(ATTR_Claim_ReasonCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Claim_ReasonCode);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskId);
                ai.setJavaName(ATTR_TaskId);
                ai.setColumnName(ATTR_TaskId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskId);
                v.setMaxLength(40);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Review_Claim_Decision);
                ai.setJavaName(ATTR_Review_Claim_Decision);
                ai.setColumnName(ATTR_Review_Claim_Decision);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Review_Claim_Decision);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ClaimNumber);
                ai.setJavaName(ATTR_ClaimNumber);
                ai.setColumnName(ATTR_ClaimNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ClaimNumber);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CM_Docid);
                ai.setJavaName(ATTR_CM_Docid);
                ai.setColumnName(ATTR_CM_Docid);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CM_Docid);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LoadDate);
                ai.setJavaName(ATTR_LoadDate);
                ai.setColumnName(ATTR_LoadDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_WorkbasketName);
                ai.setJavaName(ATTR_WorkbasketName);
                ai.setColumnName(ATTR_WorkbasketName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_WorkbasketName);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CM8_Docid);
                ai.setJavaName(ATTR_CM8_Docid);
                ai.setColumnName(ATTR_CM8_Docid);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CM8_Docid);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_IndexClass);
                ai.setJavaName(ATTR_IndexClass);
                ai.setColumnName(ATTR_IndexClass);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_IndexClass);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DocumentType);
                ai.setJavaName(ATTR_DocumentType);
                ai.setColumnName(ATTR_DocumentType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DocumentType);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Department);
                ai.setJavaName(ATTR_Department);
                ai.setColumnName(ATTR_Department);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Department);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PERID);
                ai.setJavaName(ATTR_PERID);
                ai.setColumnName(ATTR_PERID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PERID);
                v.setMaxLength(250);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DocDesc);
                ai.setJavaName(ATTR_DocDesc);
                ai.setColumnName(ATTR_DocDesc);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DocDesc);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UW_EDMDataBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getId()
    {
        return getIntProperty(ATTR_Id);
    }

    public void setId(int value)
    {
        setProperty(ATTR_Id, value, 0);
    }

    public String getUWReference()
    {
        return getStringProperty(ATTR_UWReference);
    }

    public void setUWReference(String value)
    {
        setProperty(ATTR_UWReference, value, 0);
    }

    public String getPolicy_Number()
    {
        return getStringProperty(ATTR_Policy_Number);
    }

    public void setPolicy_Number(String value)
    {
        setProperty(ATTR_Policy_Number, value, 0);
    }

    public String getName()
    {
        return getStringProperty(ATTR_Name);
    }

    public void setName(String value)
    {
        setProperty(ATTR_Name, value, 0);
    }

    public String getState()
    {
        return getStringProperty(ATTR_State);
    }

    public void setState(String value)
    {
        setProperty(ATTR_State, value, 0);
    }

    public String getDelivery_Method()
    {
        return getStringProperty(ATTR_Delivery_Method);
    }

    public void setDelivery_Method(String value)
    {
        setProperty(ATTR_Delivery_Method, value, 0);
    }

    public String getScanDate()
    {
        return getStringProperty(ATTR_ScanDate);
    }

    public void setScanDate(String value)
    {
        setProperty(ATTR_ScanDate, value, 0);
    }

    public String getPICS_CoverageCode()
    {
        return getStringProperty(ATTR_PICS_CoverageCode);
    }

    public void setPICS_CoverageCode(String value)
    {
        setProperty(ATTR_PICS_CoverageCode, value, 0);
    }

    public String getClaim_ReasonCode()
    {
        return getStringProperty(ATTR_Claim_ReasonCode);
    }

    public void setClaim_ReasonCode(String value)
    {
        setProperty(ATTR_Claim_ReasonCode, value, 0);
    }

    public String getTaskId()
    {
        return getStringProperty(ATTR_TaskId);
    }

    public void setTaskId(String value)
    {
        setProperty(ATTR_TaskId, value, 0);
    }

    public String getReview_Claim_Decision()
    {
        return getStringProperty(ATTR_Review_Claim_Decision);
    }

    public void setReview_Claim_Decision(String value)
    {
        setProperty(ATTR_Review_Claim_Decision, value, 0);
    }

    public String getClaimNumber()
    {
        return getStringProperty(ATTR_ClaimNumber);
    }

    public void setClaimNumber(String value)
    {
        setProperty(ATTR_ClaimNumber, value, 0);
    }

    public String getCM_Docid()
    {
        return getStringProperty(ATTR_CM_Docid);
    }

    public void setCM_Docid(String value)
    {
        setProperty(ATTR_CM_Docid, value, 0);
    }

    public java.util.Date getLoadDate()
    {
        return getDateTimestampProperty(ATTR_LoadDate);
    }

    public void setLoadDate(java.util.Date value)
    {
        setProperty(ATTR_LoadDate, value, 0);
    }

    public String getWorkbasketName()
    {
        return getStringProperty(ATTR_WorkbasketName);
    }

    public void setWorkbasketName(String value)
    {
        setProperty(ATTR_WorkbasketName, value, 0);
    }

    public String getCM8_Docid()
    {
        return getStringProperty(ATTR_CM8_Docid);
    }

    public void setCM8_Docid(String value)
    {
        setProperty(ATTR_CM8_Docid, value, 0);
    }

    public String getIndexClass()
    {
        return getStringProperty(ATTR_IndexClass);
    }

    public void setIndexClass(String value)
    {
        setProperty(ATTR_IndexClass, value, 0);
    }

    public String getDocumentType()
    {
        return getStringProperty(ATTR_DocumentType);
    }

    public void setDocumentType(String value)
    {
        setProperty(ATTR_DocumentType, value, 0);
    }

    public String getDepartment()
    {
        return getStringProperty(ATTR_Department);
    }

    public void setDepartment(String value)
    {
        setProperty(ATTR_Department, value, 0);
    }

    public String getPERID()
    {
        return getStringProperty(ATTR_PERID);
    }

    public void setPERID(String value)
    {
        setProperty(ATTR_PERID, value, 0);
    }

    public String getDocDesc()
    {
        return getStringProperty(ATTR_DocDesc);
    }

    public void setDocDesc(String value)
    {
        setProperty(ATTR_DocDesc, value, 0);
    }


    public static BusObjectIterator<com.cica.uw.UW_EDMData> getNextUW_EDMDataObjects(int Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"UW_EDMData\" where (\"Id\" > :Id) order by \"Id\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(Id));//NOPMD
        query.setResultClass(UW_EDMData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.UW_EDMData> getPreviousUW_EDMDataObjects(int Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"UW_EDMData\" where (\"Id\" < :Id) order by \"Id\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(Id));//NOPMD
        query.setResultClass(UW_EDMData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.cica.uw.UW_EDMData getUW_EDMDataObject(int Id)
    {
        String queryText = "select * from \"UW_EDMData\" where \"Id\" = :Id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(Id));//NOPMD
        query.setResultClass(UW_EDMData.class);
        return (UW_EDMData)query.getObject();
    }

    public static BusObjectIterator<com.cica.uw.UW_EDMData> getUW_EDMDataObjects(int fromId, int toId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"UW_EDMData\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(fromId));
        query.addParameter("toId", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(toId));
        query.setResultClass(UW_EDMData.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.cica.uw.UW_EDMData> getUW_EDMDataObjects(int fromId, int toId)
    {
        String queryText = "select * from \"UW_EDMData\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(fromId));
        query.addParameter("toId", "UW_EDMData.Id", QueryObject.PARAM_INT, new Integer(toId));
        query.setResultClass(UW_EDMData.class);
        return query.getObjects();
    }

}
