/*
  This class has been generated by the Code Generator
*/

package com.cica.uw;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class UW_SLAMasterDetails extends UW_SLAMasterDetailsBase
{
    public UW_SLAMasterDetails()
    {
        this((BusObjectConfig)null);
    }

    public UW_SLAMasterDetails(BusObjectConfig config)
    {
        super(config);
    }

}
