/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class ADLStats extends ADLStatsBase
{
    public ADLStats()
    {
        this((BusObjectConfig)null);
    }

    public ADLStats(BusObjectConfig config)
    {
        super(config);
    }

}
