/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class CompensationReviewTaskDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_Sno = "Sno";
    public final static String ATTR_MasterAppNo = "MasterAppNo";
    public final static String ATTR_AgentCode = "AgentCode";
    public final static String ATTR_Status = "Status";
    public final static String ATTR_Reason = "Reason";
    public final static String ATTR_CICACode = "CICACode";
    public final static String ATTR_NonCICACode = "NonCICACode";
    public final static String ATTR_CodeType = "CodeType";
    public final static String ATTR_RequestPayload = "RequestPayload";
    public final static String ATTR_ResponsePayload = "ResponsePayload";
    public final static String ATTR_CreatedDateTime = "CreatedDateTime";
    public final static String ATTR_TaskCreated = "TaskCreated";
    public final static String ATTR_MasterAppId = "MasterAppId";
    public final static String ATTR_AgentOfRecord = "AgentOfRecord";
    public final static String ATTR_BrokerInvolved = "BrokerInvolved";
    public final static String ATTR_EnrollerBrokerInvolved = "EnrollerBrokerInvolved";
    public final static String ATTR_CommissionType = "CommissionType";
    public final static String ATTR_AgentSplit = "AgentSplit";
    public final static String ATTR_FollowUpType = "FollowUpType";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(CompensationReviewTaskDetails.class);
            s_classInfo.setTableName("CompensationReviewTaskDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_Sno});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Sno);
                ai.setJavaName(ATTR_Sno);
                ai.setColumnName(ATTR_Sno);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_Sno);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MasterAppNo);
                ai.setJavaName(ATTR_MasterAppNo);
                ai.setColumnName(ATTR_MasterAppNo);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MasterAppNo);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AgentCode);
                ai.setJavaName(ATTR_AgentCode);
                ai.setColumnName(ATTR_AgentCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AgentCode);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Status);
                ai.setJavaName(ATTR_Status);
                ai.setColumnName(ATTR_Status);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Status);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Reason);
                ai.setJavaName(ATTR_Reason);
                ai.setColumnName(ATTR_Reason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Reason);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CICACode);
                ai.setJavaName(ATTR_CICACode);
                ai.setColumnName(ATTR_CICACode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CICACode);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_NonCICACode);
                ai.setJavaName(ATTR_NonCICACode);
                ai.setColumnName(ATTR_NonCICACode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_NonCICACode);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CodeType);
                ai.setJavaName(ATTR_CodeType);
                ai.setColumnName(ATTR_CodeType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CodeType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequestPayload);
                ai.setJavaName(ATTR_RequestPayload);
                ai.setColumnName(ATTR_RequestPayload);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequestPayload);
                v.setMaxLength(7000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ResponsePayload);
                ai.setJavaName(ATTR_ResponsePayload);
                ai.setColumnName(ATTR_ResponsePayload);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ResponsePayload);
                v.setMaxLength(7000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDateTime);
                ai.setJavaName(ATTR_CreatedDateTime);
                ai.setColumnName(ATTR_CreatedDateTime);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskCreated);
                ai.setJavaName(ATTR_TaskCreated);
                ai.setColumnName(ATTR_TaskCreated);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskCreated);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MasterAppId);
                ai.setJavaName(ATTR_MasterAppId);
                ai.setColumnName(ATTR_MasterAppId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MasterAppId);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AgentOfRecord);
                ai.setJavaName(ATTR_AgentOfRecord);
                ai.setColumnName(ATTR_AgentOfRecord);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AgentOfRecord);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_BrokerInvolved);
                ai.setJavaName(ATTR_BrokerInvolved);
                ai.setColumnName(ATTR_BrokerInvolved);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_BrokerInvolved);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_EnrollerBrokerInvolved);
                ai.setJavaName(ATTR_EnrollerBrokerInvolved);
                ai.setColumnName(ATTR_EnrollerBrokerInvolved);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_EnrollerBrokerInvolved);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CommissionType);
                ai.setJavaName(ATTR_CommissionType);
                ai.setColumnName(ATTR_CommissionType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CommissionType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AgentSplit);
                ai.setJavaName(ATTR_AgentSplit);
                ai.setColumnName(ATTR_AgentSplit);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AgentSplit);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FollowUpType);
                ai.setJavaName(ATTR_FollowUpType);
                ai.setColumnName(ATTR_FollowUpType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_FollowUpType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public CompensationReviewTaskDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSno()
    {
        return getIntProperty(ATTR_Sno);
    }

    public void setSno(int value)
    {
        setProperty(ATTR_Sno, value, 0);
    }

    public String getMasterAppNo()
    {
        return getStringProperty(ATTR_MasterAppNo);
    }

    public void setMasterAppNo(String value)
    {
        setProperty(ATTR_MasterAppNo, value, 0);
    }

    public String getAgentCode()
    {
        return getStringProperty(ATTR_AgentCode);
    }

    public void setAgentCode(String value)
    {
        setProperty(ATTR_AgentCode, value, 0);
    }

    public String getStatus()
    {
        return getStringProperty(ATTR_Status);
    }

    public void setStatus(String value)
    {
        setProperty(ATTR_Status, value, 0);
    }

    public String getReason()
    {
        return getStringProperty(ATTR_Reason);
    }

    public void setReason(String value)
    {
        setProperty(ATTR_Reason, value, 0);
    }

    public String getCICACode()
    {
        return getStringProperty(ATTR_CICACode);
    }

    public void setCICACode(String value)
    {
        setProperty(ATTR_CICACode, value, 0);
    }

    public String getNonCICACode()
    {
        return getStringProperty(ATTR_NonCICACode);
    }

    public void setNonCICACode(String value)
    {
        setProperty(ATTR_NonCICACode, value, 0);
    }

    public String getCodeType()
    {
        return getStringProperty(ATTR_CodeType);
    }

    public void setCodeType(String value)
    {
        setProperty(ATTR_CodeType, value, 0);
    }

    public String getRequestPayload()
    {
        return getStringProperty(ATTR_RequestPayload);
    }

    public void setRequestPayload(String value)
    {
        setProperty(ATTR_RequestPayload, value, 0);
    }

    public String getResponsePayload()
    {
        return getStringProperty(ATTR_ResponsePayload);
    }

    public void setResponsePayload(String value)
    {
        setProperty(ATTR_ResponsePayload, value, 0);
    }

    public java.util.Date getCreatedDateTime()
    {
        return getDateTimestampProperty(ATTR_CreatedDateTime);
    }

    public void setCreatedDateTime(java.util.Date value)
    {
        setProperty(ATTR_CreatedDateTime, value, 0);
    }

    public String getTaskCreated()
    {
        return getStringProperty(ATTR_TaskCreated);
    }

    public void setTaskCreated(String value)
    {
        setProperty(ATTR_TaskCreated, value, 0);
    }

    public String getMasterAppId()
    {
        return getStringProperty(ATTR_MasterAppId);
    }

    public void setMasterAppId(String value)
    {
        setProperty(ATTR_MasterAppId, value, 0);
    }

    public String getAgentOfRecord()
    {
        return getStringProperty(ATTR_AgentOfRecord);
    }

    public void setAgentOfRecord(String value)
    {
        setProperty(ATTR_AgentOfRecord, value, 0);
    }

    public String getBrokerInvolved()
    {
        return getStringProperty(ATTR_BrokerInvolved);
    }

    public void setBrokerInvolved(String value)
    {
        setProperty(ATTR_BrokerInvolved, value, 0);
    }

    public String getEnrollerBrokerInvolved()
    {
        return getStringProperty(ATTR_EnrollerBrokerInvolved);
    }

    public void setEnrollerBrokerInvolved(String value)
    {
        setProperty(ATTR_EnrollerBrokerInvolved, value, 0);
    }

    public String getCommissionType()
    {
        return getStringProperty(ATTR_CommissionType);
    }

    public void setCommissionType(String value)
    {
        setProperty(ATTR_CommissionType, value, 0);
    }

    public String getAgentSplit()
    {
        return getStringProperty(ATTR_AgentSplit);
    }

    public void setAgentSplit(String value)
    {
        setProperty(ATTR_AgentSplit, value, 0);
    }

    public String getFollowUpType()
    {
        return getStringProperty(ATTR_FollowUpType);
    }

    public void setFollowUpType(String value)
    {
        setProperty(ATTR_FollowUpType, value, 0);
    }



    public static com.worksitewsapppackage.CompensationReviewTaskDetails getCompensationReviewTaskDetailsObject(int Sno)
    {
        String queryText = "select * from \"CompensationReviewTaskDetails\" where \"Sno\" = :Sno";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Sno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(Sno));//NOPMD
        query.setResultClass(CompensationReviewTaskDetails.class);
        return (CompensationReviewTaskDetails)query.getObject();
    }

    public static BusObjectIterator<com.worksitewsapppackage.CompensationReviewTaskDetails> getCompensationReviewTaskDetailsObjects(int fromSno, int toSno, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"CompensationReviewTaskDetails\" where \"Sno\" between :fromSno and :toSno";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(fromSno));
        query.addParameter("toSno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(toSno));
        query.setResultClass(CompensationReviewTaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.CompensationReviewTaskDetails> getCompensationReviewTaskDetailsObjects(int fromSno, int toSno)
    {
        String queryText = "select * from \"CompensationReviewTaskDetails\" where \"Sno\" between :fromSno and :toSno";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(fromSno));
        query.addParameter("toSno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(toSno));
        query.setResultClass(CompensationReviewTaskDetails.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.CompensationReviewTaskDetails> getNextCompensationReviewTaskDetailsObjects(int Sno, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"CompensationReviewTaskDetails\" where (\"Sno\" > :Sno) order by \"Sno\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Sno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(Sno));//NOPMD
        query.setResultClass(CompensationReviewTaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.CompensationReviewTaskDetails> getPreviousCompensationReviewTaskDetailsObjects(int Sno, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"CompensationReviewTaskDetails\" where (\"Sno\" < :Sno) order by \"Sno\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Sno", "CompensationReviewTaskDetails.Sno", QueryObject.PARAM_INT, new Integer(Sno));//NOPMD
        query.setResultClass(CompensationReviewTaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

}
