/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class FirstBill_Notification_Details extends FirstBill_Notification_DetailsBase
{
    public FirstBill_Notification_Details()
    {
        this((BusObjectConfig)null);
    }

    public FirstBill_Notification_Details(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.worksitewsapppackage.FirstBill_Notification_Details> getOneMonthRecordsforFirstBill()
    {
         String querytext= "SELECT * FROM FirstBill_Notification_Details WHERE CaseCreatedDate >= DATEADD(month, DATEDIFF(month, 0, GETDATE())-1, 25) AND CaseCreatedDate < DATEADD(month, DATEDIFF(month, 0, GETDATE()), 25)";
        QueryObject query = new QueryObject(querytext);
        query.setResultClass(FirstBill_Notification_Details.class);
		return query.getObjects();
    }

}
