/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.xml.nom.Node;
import com.eibus.xml.xpath.XPath;
import com.cordys.cpc.bsf.busobject.BusObject;

public class LSPMaster extends LSPMasterBase
{
    public LSPMaster()
    {
        this((BusObjectConfig)null);
    }

    public LSPMaster(BusObjectConfig config)
    {
        super(config);
    }

public static BusObjectIterator<com.cordys.cpc.bsf.busobject.BusObject> fetchOnlyCompleteOrNAUsingMtrAppNo(String Master_App_No)
    {
BusObjectIterator <BusObject> resp1 = null;
		String queryText = "select * from LSPMaster where Status not in ('COMPLETED','NOT APPLICABLE') and MasterAppNumber='"+Master_App_No+"' ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("MasterAppNumber", "LSPMaster.MasterAppNumber", QueryObject.PARAM_STRING, Master_App_No);
        query.setResultClass(LSPMaster.class);
      //  int resp= query.getObjects();
		BusObject busObj = query.getObject();
	//	String Screen_Name = busObj.getStringProperty("ScreenName");
		
		if(busObj == null ) 
		{
		String queryText1 = "select * from LSPMaster where Status in ('COMPLETED','NOT APPLICABLE') and MasterAppNumber='"+Master_App_No+"' ";
        QueryObject query1 = new QueryObject(queryText1);
        query1.addParameter("MasterAppNumber", "LSPMaster.MasterAppNumber", QueryObject.PARAM_STRING, Master_App_No);
        query1.setResultClass(LSPMaster.class);
      resp1= query1.getObjects();
		}
		
		return resp1;
    }
	
 public static BusObjectIterator<com.worksitewsapppackage.LSPMaster> getLSPWimsDataCountMatchedRows(String idd)
    {
       String queryText1 = "select * from LSPMaster LSM join WIMSDataRequest WDR on WDR.MasterAppNumber=LSM.MasterAppNumber and WDR.header=LSM.Header and WDR.AttemptNumber=LSM.RecentAttempt where LSM.Status in ('SCREEN ERROR','DATA ERROR') and LSM.MasterAppNumber='"+idd+"'";
        QueryObject query1 = new QueryObject(queryText1);
       query1.addParameter("MasterAppNumber", "LSPMaster.MasterAppNumber", QueryObject.PARAM_STRING, idd);
        query1.setResultClass(LSPMaster.class);
      return query1.getObjects();
    }
 public static BusObjectIterator<com.worksitewsapppackage.LSPMaster> getScreensByMasterID(String MasterID)
    {
       String queryText1 = "select distinct Header from LSPMaster where MasterAppNumber=MasterID";
        QueryObject query1 = new QueryObject(queryText1);
       
        query1.setResultClass(LSPMaster.class);
      return query1.getObjects();
    }

}

