/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import java.io.FileOutputStream;

import com.cordys.cpc.bsf.busobject.BusObject;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.eibus.util.system.EIBProperties;
import com.eibus.xml.nom.Node;
import com.eibus.xml.xpath.XPath;
import com.itextpdf.awt.geom.Rectangle;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.cordys.cpc.bsf.soap.SOAPRequestObject;


public class PDFRenderDetails extends PDFRenderDetailsBase
{
    public PDFRenderDetails()
    {
        this((BusObjectConfig)null);
    }

    public PDFRenderDetails(BusObjectConfig config)
    {
        super(config);
    }
	public static String getPDFDocumentContent(String masterAppNo,String masterAppId)
 	 {
		String saveFilePath="";
                //Added by Chaithanya for OT Upgrade Migration for File path changes
                String fileInDir = "";
                String args[]={"key"};
		String values[]={"com/cica/worksite/Saleforce_Configurations.xml"};
		SOAPRequestObject srObj=null;
		int response=-1;boolean flag=false;
                srObj=new SOAPRequestObject("http://schemas.cordys.com/1.0/xmlstore","GetXMLObject",args,values);
                response=srObj.sendAndWait();
		fileInDir = Node.getData(XPath.getFirstMatch(".//*[local-name()='Install_DIR']",null,response));
                
		try{
			String FileName1 = masterAppNo+"_Salesforce.pdf";
                        
                         //saveFilePath = EIBProperties.getInstallDir()+"\\webroot\\shared\\WorkSite\\"+FileName1 ;            //Commented for OT Upgrade Project Changes
                        saveFilePath = fileInDir+"\\WorkSite\\"+FileName1 ;                                                                      //Added by Chaithanya for OT Upgrade Migration for Filepath changes
			int masterAppNode = WorksiteUtil.getMasterAppObjectById(masterAppId);
			int accountNode = XPath.getFirstMatch(".//*[local-name()='AccountData']",null,masterAppNode);
			int opportunityNode = XPath.getFirstMatch(".//*[local-name()='OpportunityData']",null,masterAppNode);
			int masterSubNode= XPath.getFirstMatch(".//*[local-name()='MasterApplication']",null,masterAppNode);
			String columnQueryText="Select distinct HeaderId from PDFRenderDetails ";
			QueryObject columnQueryobj=new QueryObject(columnQueryText);
			BusObjectIterator<BusObject> columnObject= columnQueryobj.getObjects();
			 Document doc = new Document();
		        // step 2
		        PdfWriter writer =
		            PdfWriter.getInstance(doc, new FileOutputStream(saveFilePath));
		        // step 3
		        doc.open();
		        // step 4
		        Paragraph p = new Paragraph(masterAppNo, new Font(FontFamily.TIMES_ROMAN,16,Font.BOLD));
		        p.setAlignment(Element.ALIGN_CENTER);
		        doc.add(p);
			while(columnObject.hasMoreElements()) {
				String coulmnName="",tableCoulmn="";
				int columnId=0;
				BusObject coulmnobj = columnObject.nextElement();
				columnId = coulmnobj.getIntProperty("HeaderId");
				String queryText="select  * from PDFRenderDetails where HeaderId='"+columnId+"'";
				QueryObject queryobj=new QueryObject(queryText);
				String coulmnText="select distinct HeaderName from PDFRenderDetails where HeaderId='"+columnId+"'";
				QueryObject coulmnQueryObj=new QueryObject(coulmnText);
				BusObject coulmnNameObj = coulmnQueryObj.getObject();
				tableCoulmn = coulmnNameObj.getStringProperty("HeaderName");
				BusObjectIterator<BusObject> object= queryobj.getObjects();
				Paragraph pa = new Paragraph(tableCoulmn, new Font(FontFamily.TIMES_ROMAN,14,Font.BOLD));
		        pa.setAlignment(Element.ALIGN_LEFT);
		        doc.add(pa);
				while(object.hasMoreElements()) {
					
					BusObject obj = object.nextElement();
					String lableName = "",rootTagName="",tagName="",fieldValue="";
					lableName=obj.getStringProperty("LableName");
					rootTagName=obj.getStringProperty("RootTagName");
					tagName = obj.getStringProperty("TagName");
					if(rootTagName.equalsIgnoreCase("MasterApplication"))
						fieldValue = (Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,masterSubNode))==null?"":Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,masterSubNode)));
					else if(rootTagName.equalsIgnoreCase("OpportunityDetails"))
							fieldValue = (Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,opportunityNode))==null?"":Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,opportunityNode)));
					else
						fieldValue = (Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,accountNode))==null?"":Node.getData(XPath.getFirstMatch(".//*[local-name()='"+tagName+"']",null,accountNode)));
					PdfPTable tbl = new PdfPTable(2);
			        tbl.setWidthPercentage(100);
			        tbl.setWidths(new int[]{150, 350});
			        Font normal = new Font(FontFamily.TIMES_ROMAN,8);
			        Font label = new Font(FontFamily.TIMES_ROMAN,8,Font.BOLD);
		        	PdfPCell cell = new PdfPCell(new Phrase(lableName,label));
		            cell.setHorizontalAlignment(Element.ALIGN_LEFT);
		            cell.disableBorderSide(Rectangle.OUT_BOTTOM);
		            cell.disableBorderSide(Rectangle.OUT_LEFT);
		            cell.disableBorderSide(Rectangle.OUT_RIGHT);
		            cell.disableBorderSide(Rectangle.OUT_TOP);
		            tbl.addCell(cell);
		            cell = new PdfPCell(new Phrase(fieldValue,normal));
		            cell.setHorizontalAlignment(Element.PTABLE);
		            cell.disableBorderSide(Rectangle.OUT_BOTTOM);
		            cell.disableBorderSide(Rectangle.OUT_LEFT);
		            cell.disableBorderSide(Rectangle.OUT_RIGHT);
		            cell.disableBorderSide(Rectangle.OUT_TOP);
		            tbl.addCell(cell);
			        p = new Paragraph();

			  	     p.add(tbl);
			  	   doc.add(p); 

				}
			}
	        // step 5
	  	 doc.close();
	    	}
	    	catch(Exception e) {}
 		 
 		 return saveFilePath;
 	 }


}
