/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;


public class SLA_Table extends SLA_TableBase
{
    public SLA_Table()
    {
        this((BusObjectConfig)null);
    }

    public SLA_Table(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.worksitewsapppackage.SLA_Table> getSLADetailsByStatus()
    {
        String queryText = "select * from SLA_Table where Status = 'Active'";
        QueryObject query = new QueryObject(queryText);
        //query.addParameter("Status", "SLA_Table.Status", QueryObject.PARAM_STRING, Status);//NOPMD
        query.setResultClass(SLA_Table.class);
        return query.getObjects();
    }

}
