/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class TaskDetailsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_Id = "Id";
    public final static String ATTR_TaskInstanceId = "TaskInstanceId";
    public final static String ATTR_TaskName = "TaskName";
    public final static String ATTR_MasterAppNumber = "MasterAppNumber";
    public final static String ATTR_GroupNumber = "GroupNumber";
    public final static String ATTR_CompanyCode = "CompanyCode";
    public final static String ATTR_AppNumber = "AppNumber";
    public final static String ATTR_TeamName = "TeamName";
    public final static String ATTR_Reason = "Reason";
    public final static String ATTR_DueDate = "DueDate";
    public final static String ATTR_ReqType = "ReqType";
    public final static String ATTR_ReqNotes = "ReqNotes";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_CaseId = "CaseId";
    public final static String ATTR_linkedTask = "linkedTask";
    public final static String ATTR_TaskStatus = "TaskStatus";
    public final static String ATTR_linkedTaskId = "linkedTaskId";
    public final static String ATTR_CancellationReason = "CancellationReason";
    public final static String ATTR_CancellationCode = "CancellationCode";
    public final static String ATTR_RequesterDN = "RequesterDN";
    public final static String ATTR_ParentTaskType = "ParentTaskType";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_UpdatedDate = "UpdatedDate";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(TaskDetails.class);
            s_classInfo.setTableName("TaskDetails");
            s_classInfo.setUIDElements(new String[]{ATTR_Id});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Id);
                ai.setJavaName(ATTR_Id);
                ai.setColumnName(ATTR_Id);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_Id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskInstanceId);
                ai.setJavaName(ATTR_TaskInstanceId);
                ai.setColumnName(ATTR_TaskInstanceId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskInstanceId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskName);
                ai.setJavaName(ATTR_TaskName);
                ai.setColumnName(ATTR_TaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskName);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_MasterAppNumber);
                ai.setJavaName(ATTR_MasterAppNumber);
                ai.setColumnName(ATTR_MasterAppNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_MasterAppNumber);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GroupNumber);
                ai.setJavaName(ATTR_GroupNumber);
                ai.setColumnName(ATTR_GroupNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GroupNumber);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompanyCode);
                ai.setJavaName(ATTR_CompanyCode);
                ai.setColumnName(ATTR_CompanyCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompanyCode);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AppNumber);
                ai.setJavaName(ATTR_AppNumber);
                ai.setColumnName(ATTR_AppNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AppNumber);
                v.setMaxLength(20);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TeamName);
                ai.setJavaName(ATTR_TeamName);
                ai.setColumnName(ATTR_TeamName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TeamName);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Reason);
                ai.setJavaName(ATTR_Reason);
                ai.setColumnName(ATTR_Reason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Reason);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DueDate);
                ai.setJavaName(ATTR_DueDate);
                ai.setColumnName(ATTR_DueDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReqType);
                ai.setJavaName(ATTR_ReqType);
                ai.setColumnName(ATTR_ReqType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ReqType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReqNotes);
                ai.setJavaName(ATTR_ReqNotes);
                ai.setColumnName(ATTR_ReqNotes);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ReqNotes);
                v.setMaxLength(1000);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(150);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CaseId);
                ai.setJavaName(ATTR_CaseId);
                ai.setColumnName(ATTR_CaseId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CaseId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_linkedTask);
                ai.setJavaName(ATTR_linkedTask);
                ai.setColumnName(ATTR_linkedTask);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_linkedTask);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskStatus);
                ai.setJavaName(ATTR_TaskStatus);
                ai.setColumnName(ATTR_TaskStatus);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskStatus);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_linkedTaskId);
                ai.setJavaName(ATTR_linkedTaskId);
                ai.setColumnName(ATTR_linkedTaskId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_linkedTaskId);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationReason);
                ai.setJavaName(ATTR_CancellationReason);
                ai.setColumnName(ATTR_CancellationReason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationReason);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationCode);
                ai.setJavaName(ATTR_CancellationCode);
                ai.setColumnName(ATTR_CancellationCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationCode);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RequesterDN);
                ai.setJavaName(ATTR_RequesterDN);
                ai.setColumnName(ATTR_RequesterDN);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_RequesterDN);
                v.setMaxLength(200);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ParentTaskType);
                ai.setJavaName(ATTR_ParentTaskType);
                ai.setColumnName(ATTR_ParentTaskType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ParentTaskType);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedDate);
                ai.setJavaName(ATTR_UpdatedDate);
                ai.setColumnName(ATTR_UpdatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public TaskDetailsBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getId()
    {
        return getLongProperty(ATTR_Id);
    }

    public void setId(long value)
    {
        setProperty(ATTR_Id, value, 0);
    }

    public String getTaskInstanceId()
    {
        return getStringProperty(ATTR_TaskInstanceId);
    }

    public void setTaskInstanceId(String value)
    {
        setProperty(ATTR_TaskInstanceId, value, 0);
    }

    public String getTaskName()
    {
        return getStringProperty(ATTR_TaskName);
    }

    public void setTaskName(String value)
    {
        setProperty(ATTR_TaskName, value, 0);
    }

    public String getMasterAppNumber()
    {
        return getStringProperty(ATTR_MasterAppNumber);
    }

    public void setMasterAppNumber(String value)
    {
        setProperty(ATTR_MasterAppNumber, value, 0);
    }

    public String getGroupNumber()
    {
        return getStringProperty(ATTR_GroupNumber);
    }

    public void setGroupNumber(String value)
    {
        setProperty(ATTR_GroupNumber, value, 0);
    }

    public String getCompanyCode()
    {
        return getStringProperty(ATTR_CompanyCode);
    }

    public void setCompanyCode(String value)
    {
        setProperty(ATTR_CompanyCode, value, 0);
    }

    public String getAppNumber()
    {
        return getStringProperty(ATTR_AppNumber);
    }

    public void setAppNumber(String value)
    {
        setProperty(ATTR_AppNumber, value, 0);
    }

    public String getTeamName()
    {
        return getStringProperty(ATTR_TeamName);
    }

    public void setTeamName(String value)
    {
        setProperty(ATTR_TeamName, value, 0);
    }

    public String getReason()
    {
        return getStringProperty(ATTR_Reason);
    }

    public void setReason(String value)
    {
        setProperty(ATTR_Reason, value, 0);
    }

    public java.util.Date getDueDate()
    {
        return getDateTimestampProperty(ATTR_DueDate);
    }

    public void setDueDate(java.util.Date value)
    {
        setProperty(ATTR_DueDate, value, 0);
    }

    public String getReqType()
    {
        return getStringProperty(ATTR_ReqType);
    }

    public void setReqType(String value)
    {
        setProperty(ATTR_ReqType, value, 0);
    }

    public String getReqNotes()
    {
        return getStringProperty(ATTR_ReqNotes);
    }

    public void setReqNotes(String value)
    {
        setProperty(ATTR_ReqNotes, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public java.util.Date getCreatedDate()
    {
        return getDateTimestampProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.util.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getCaseId()
    {
        return getStringProperty(ATTR_CaseId);
    }

    public void setCaseId(String value)
    {
        setProperty(ATTR_CaseId, value, 0);
    }

    public String getLinkedTask()
    {
        return getStringProperty(ATTR_linkedTask);
    }

    public void setLinkedTask(String value)
    {
        setProperty(ATTR_linkedTask, value, 0);
    }

    public String getTaskStatus()
    {
        return getStringProperty(ATTR_TaskStatus);
    }

    public void setTaskStatus(String value)
    {
        setProperty(ATTR_TaskStatus, value, 0);
    }

    public String getLinkedTaskId()
    {
        return getStringProperty(ATTR_linkedTaskId);
    }

    public void setLinkedTaskId(String value)
    {
        setProperty(ATTR_linkedTaskId, value, 0);
    }

    public String getCancellationReason()
    {
        return getStringProperty(ATTR_CancellationReason);
    }

    public void setCancellationReason(String value)
    {
        setProperty(ATTR_CancellationReason, value, 0);
    }

    public String getCancellationCode()
    {
        return getStringProperty(ATTR_CancellationCode);
    }

    public void setCancellationCode(String value)
    {
        setProperty(ATTR_CancellationCode, value, 0);
    }

    public String getRequesterDN()
    {
        return getStringProperty(ATTR_RequesterDN);
    }

    public void setRequesterDN(String value)
    {
        setProperty(ATTR_RequesterDN, value, 0);
    }

    public String getParentTaskType()
    {
        return getStringProperty(ATTR_ParentTaskType);
    }

    public void setParentTaskType(String value)
    {
        setProperty(ATTR_ParentTaskType, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getUpdatedDate()
    {
        return getDateTimestampProperty(ATTR_UpdatedDate);
    }

    public void setUpdatedDate(java.util.Date value)
    {
        setProperty(ATTR_UpdatedDate, value, 0);
    }



    public static BusObjectIterator<com.worksitewsapppackage.TaskDetails> getNextTaskDetailsObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TaskDetails\" where (\"Id\" > :Id) order by \"Id\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.TaskDetails> getPreviousTaskDetailsObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TaskDetails\" where (\"Id\" < :Id) order by \"Id\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }



    public static com.worksitewsapppackage.TaskDetails getTaskDetailsObject(long Id)
    {
        String queryText = "select * from \"TaskDetails\" where \"Id\" = :Id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(TaskDetails.class);
        return (TaskDetails)query.getObject();
    }

    public static BusObjectIterator<com.worksitewsapppackage.TaskDetails> getTaskDetailsObjects(long fromId, long toId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"TaskDetails\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(TaskDetails.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.TaskDetails> getTaskDetailsObjects(long fromId, long toId)
    {
        String queryText = "select * from \"TaskDetails\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "TaskDetails.Id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(TaskDetails.class);
        return query.getObjects();
    }




}
