/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.soap.SOAPRequestObject;
import java.util.*;
import java.text.*;


public class UW_ActivityLog extends UW_ActivityLogBase
{
    public UW_ActivityLog()
    {
        this((BusObjectConfig)null);
    }

    public UW_ActivityLog(BusObjectConfig config)
    {
        super(config);
    }

    public static String GetDateTimeForStringDate(String existingDate)
    {
        Date date = new Date(existingDate);
SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

String formattedDate=sdf.format(date.getTime());
        return formattedDate;
    }

    public static BusObjectIterator<com.worksitewsapppackage.UW_ActivityLog> getexistingcasedetails(String caseinstanceid, String activitytype, String workitem, String performedby, String olddescription, String newdescription, java.util.Date datetime)
    {
        String queryText = "SELECT * FROM UW_ActivityLog WHERE CaseInstanceID= :caseinstanceid AND ActivityType= :activitytype AND WorkItem= :workitem AND PerformedBy= :performedby AND OldDescription= :olddescription AND NewDescription= :newdescription AND DateAndTime= :datetime ORDER BY DateAndTime DESC";
			QueryObject query = new QueryObject(queryText);
			query.addParameter("caseinstanceid", "UW_ActivityLog.CaseInstanceID", QueryObject.PARAM_STRING, caseinstanceid);//NOPMD
			query.addParameter("activitytype", "UW_ActivityLog.ActivityType", QueryObject.PARAM_STRING, activitytype);//NOPMD
			query.addParameter("workitem", "UW_ActivityLog.WorkItem", QueryObject.PARAM_STRING, workitem);//NOPMD
			query.addParameter("performedby", "UW_ActivityLog.PerformedBy", QueryObject.PARAM_STRING, performedby);//NOPMD
			query.addParameter("olddescription", "UW_ActivityLog.OldDescription", QueryObject.PARAM_STRING, olddescription);//NOPMD
			query.addParameter("newdescription", "UW_ActivityLog.NewDescription", QueryObject.PARAM_STRING, newdescription);//NOPMD
			query.addParameter("datetime", "UW_ActivityLog.DateAndTime", QueryObject.PARAM_STRING, datetime);//NOPMD
        
        query.setResultClass(UW_ActivityLog.class);
        return query.getObjects();
    }

}
