/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import java.util.*;
import com.cordys.cpc.bsf.busobject.BSF;

public class WKSAPPQUESTION extends WKSAPPQUESTIONBase
{
    public WKSAPPQUESTION()
    {
        this((BusObjectConfig)null);
    }

    public WKSAPPQUESTION(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSAPPQUESTION> GetAppQuestionsByProdNum(String ProductNumber, String State)
    {
         String queryText = "select * from \"WKSAPPQUESTION\" where \"ProductNumber\" = :ProductNumber and State = :State and  (EmpQnFld <> '' or SpsQnFld <> '' or ChildQnFld <> '' ) ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ProductNumber", "WKSAPPQUESTION.ProductNumber", QueryObject.PARAM_STRING, ProductNumber);//NOPMD
         query.addParameter("State", "WKSAPPQUESTION.State", QueryObject.PARAM_STRING, State);//NOPMD
        query.setResultClass(WKSAPPQUESTION.class);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSAPPQUESTION> GetMedicalDisclouserForProductNo(String ProductNumber, String State)
    {
        String queryText = "select * from \"WKSAPPQUESTION\" where \"ProductNumber\" = :ProductNumber and State = :State and  (PatientName <> '' or Condition_Illness <> '' or PhyscianAddrress <> '' or PhysicianName <> '') ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ProductNumber", "WKSAPPQUESTION.ProductNumber", QueryObject.PARAM_STRING, ProductNumber);//NOPMD
         query.addParameter("State", "WKSAPPQUESTION.State", QueryObject.PARAM_STRING, State);//NOPMD
        query.setResultClass(WKSAPPQUESTION.class);
        return query.getObjects();
    }
    public static BusObjectIterator<com.worksitewsapppackage.WKSAPPQUESTION> GetVendorProdQues(String ProductNumber, String State)
    {
       String queryText = "select * from \"WKSAPPQUESTION\" where \"ProductNumber\" = :ProductNumber and State = :State ";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("ProductNumber", "WKSAPPQUESTION.ProductNumber", QueryObject.PARAM_STRING, ProductNumber);//NOPMD
         query.addParameter("State", "WKSAPPQUESTION.State", QueryObject.PARAM_STRING, State);//NOPMD
        query.setResultClass(WKSAPPQUESTION.class);
        return query.getObjects();
    }

}
