/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class WksEnrollmentTaskAssignmentsBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_Id = "Id";
    public final static String ATTR_Taskname = "Taskname";
    public final static String ATTR_TargetType1 = "TargetType1";
    public final static String ATTR_DefaultAssignee1 = "DefaultAssignee1";
    public final static String ATTR_AssignedTo1 = "AssignedTo1";
    public final static String ATTR_TargetType2 = "TargetType2";
    public final static String ATTR_DefaultAssignee2 = "DefaultAssignee2";
    public final static String ATTR_AssignedTo2 = "AssignedTo2";
    public final static String ATTR_Autorouting = "Autorouting";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(WksEnrollmentTaskAssignments.class);
            s_classInfo.setTableName("WksEnrollmentTaskAssignments");
            s_classInfo.setUIDElements(new String[]{ATTR_Id});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Id);
                ai.setJavaName(ATTR_Id);
                ai.setColumnName(ATTR_Id);
                ai.setAttributeClass(long.class);
                NumberValidator v = new NumberValidator(ATTR_Id);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Taskname);
                ai.setJavaName(ATTR_Taskname);
                ai.setColumnName(ATTR_Taskname);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Taskname);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TargetType1);
                ai.setJavaName(ATTR_TargetType1);
                ai.setColumnName(ATTR_TargetType1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TargetType1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DefaultAssignee1);
                ai.setJavaName(ATTR_DefaultAssignee1);
                ai.setColumnName(ATTR_DefaultAssignee1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DefaultAssignee1);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AssignedTo1);
                ai.setJavaName(ATTR_AssignedTo1);
                ai.setColumnName(ATTR_AssignedTo1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AssignedTo1);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TargetType2);
                ai.setJavaName(ATTR_TargetType2);
                ai.setColumnName(ATTR_TargetType2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TargetType2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DefaultAssignee2);
                ai.setJavaName(ATTR_DefaultAssignee2);
                ai.setColumnName(ATTR_DefaultAssignee2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_DefaultAssignee2);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AssignedTo2);
                ai.setJavaName(ATTR_AssignedTo2);
                ai.setColumnName(ATTR_AssignedTo2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_AssignedTo2);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Autorouting);
                ai.setJavaName(ATTR_Autorouting);
                ai.setColumnName(ATTR_Autorouting);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Autorouting);
                v.setMaxLength(3);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public WksEnrollmentTaskAssignmentsBase(BusObjectConfig config)
    {
        super(config);
    }

    public long getId()
    {
        return getLongProperty(ATTR_Id);
    }

    public void setId(long value)
    {
        setProperty(ATTR_Id, value, 0);
    }

    public String getTaskname()
    {
        return getStringProperty(ATTR_Taskname);
    }

    public void setTaskname(String value)
    {
        setProperty(ATTR_Taskname, value, 0);
    }

    public String getTargetType1()
    {
        return getStringProperty(ATTR_TargetType1);
    }

    public void setTargetType1(String value)
    {
        setProperty(ATTR_TargetType1, value, 0);
    }

    public String getDefaultAssignee1()
    {
        return getStringProperty(ATTR_DefaultAssignee1);
    }

    public void setDefaultAssignee1(String value)
    {
        setProperty(ATTR_DefaultAssignee1, value, 0);
    }

    public String getAssignedTo1()
    {
        return getStringProperty(ATTR_AssignedTo1);
    }

    public void setAssignedTo1(String value)
    {
        setProperty(ATTR_AssignedTo1, value, 0);
    }

    public String getTargetType2()
    {
        return getStringProperty(ATTR_TargetType2);
    }

    public void setTargetType2(String value)
    {
        setProperty(ATTR_TargetType2, value, 0);
    }

    public String getDefaultAssignee2()
    {
        return getStringProperty(ATTR_DefaultAssignee2);
    }

    public void setDefaultAssignee2(String value)
    {
        setProperty(ATTR_DefaultAssignee2, value, 0);
    }

    public String getAssignedTo2()
    {
        return getStringProperty(ATTR_AssignedTo2);
    }

    public void setAssignedTo2(String value)
    {
        setProperty(ATTR_AssignedTo2, value, 0);
    }

    public String getAutorouting()
    {
        return getStringProperty(ATTR_Autorouting);
    }

    public void setAutorouting(String value)
    {
        setProperty(ATTR_Autorouting, value, 0);
    }

    public static BusObjectIterator<com.worksitewsapppackage.WksEnrollmentTaskAssignments> getNextWksEnrollmentTaskAssignmentsObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WksEnrollmentTaskAssignments\" where (\"Id\" > :Id) order by \"Id\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(WksEnrollmentTaskAssignments.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WksEnrollmentTaskAssignments> getPreviousWksEnrollmentTaskAssignmentsObjects(long Id, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WksEnrollmentTaskAssignments\" where (\"Id\" < :Id) order by \"Id\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(WksEnrollmentTaskAssignments.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.worksitewsapppackage.WksEnrollmentTaskAssignments getWksEnrollmentTaskAssignmentsObject(long Id)
    {
        String queryText = "select * from \"WksEnrollmentTaskAssignments\" where \"Id\" = :Id";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("Id", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(Id));//NOPMD
        query.setResultClass(WksEnrollmentTaskAssignments.class);
        return (WksEnrollmentTaskAssignments)query.getObject();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WksEnrollmentTaskAssignments> getWksEnrollmentTaskAssignmentsObjects(long fromId, long toId, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WksEnrollmentTaskAssignments\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(WksEnrollmentTaskAssignments.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WksEnrollmentTaskAssignments> getWksEnrollmentTaskAssignmentsObjects(long fromId, long toId)
    {
        String queryText = "select * from \"WksEnrollmentTaskAssignments\" where \"Id\" between :fromId and :toId";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromId", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(fromId));
        query.addParameter("toId", "WksEnrollmentTaskAssignments.Id", QueryObject.PARAM_INT, new Long(toId));
        query.setResultClass(WksEnrollmentTaskAssignments.class);
        return query.getObjects();
    }

}
