/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class WKSOPSCaseTmp extends WKSOPSCaseTmpBase
{
    public WKSOPSCaseTmp()
    {
        this((BusObjectConfig)null);
    }

    public WKSOPSCaseTmp(BusObjectConfig config)
    {
        super(config);
    }

}
