/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class WKSOPsCaseHandlingConfigBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SLNO = "SLNO";
    public final static String ATTR_PLANNAME = "PLANNAME";
    public final static String ATTR_STATE = "STATE";
    public final static String ATTR_TYPE1 = "TYPE1";
    public final static String ATTR_TYPE2 = "TYPE2";
    public final static String ATTR_TYPE3 = "TYPE3";
    public final static String ATTR_TYPE4 = "TYPE4";
    public final static String ATTR_TYPE5 = "TYPE5";
    public final static String ATTR_PLANID = "PLANID";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_UpdatedDate = "UpdatedDate";
    public final static String ATTR_CaseType = "CaseType";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(WKSOPsCaseHandlingConfig.class);
            s_classInfo.setTableName("WKSOPsCaseHandlingConfig");
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SLNO);
                ai.setJavaName(ATTR_SLNO);
                ai.setColumnName(ATTR_SLNO);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SLNO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PLANNAME);
                ai.setJavaName(ATTR_PLANNAME);
                ai.setColumnName(ATTR_PLANNAME);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PLANNAME);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_STATE);
                ai.setJavaName(ATTR_STATE);
                ai.setColumnName(ATTR_STATE);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_STATE);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TYPE1);
                ai.setJavaName(ATTR_TYPE1);
                ai.setColumnName(ATTR_TYPE1);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TYPE1);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TYPE2);
                ai.setJavaName(ATTR_TYPE2);
                ai.setColumnName(ATTR_TYPE2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TYPE2);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TYPE3);
                ai.setJavaName(ATTR_TYPE3);
                ai.setColumnName(ATTR_TYPE3);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TYPE3);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TYPE4);
                ai.setJavaName(ATTR_TYPE4);
                ai.setColumnName(ATTR_TYPE4);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TYPE4);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TYPE5);
                ai.setJavaName(ATTR_TYPE5);
                ai.setColumnName(ATTR_TYPE5);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TYPE5);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PLANID);
                ai.setJavaName(ATTR_PLANID);
                ai.setColumnName(ATTR_PLANID);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_PLANID);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(60);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedDate);
                ai.setJavaName(ATTR_UpdatedDate);
                ai.setColumnName(ATTR_UpdatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CaseType);
                ai.setJavaName(ATTR_CaseType);
                ai.setColumnName(ATTR_CaseType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CaseType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public WKSOPsCaseHandlingConfigBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSLNO()
    {
        return getIntProperty(ATTR_SLNO);
    }

    public void setSLNO(int value)
    {
        setProperty(ATTR_SLNO, value, 0);
    }

    public String getPLANNAME()
    {
        return getStringProperty(ATTR_PLANNAME);
    }

    public void setPLANNAME(String value)
    {
        setProperty(ATTR_PLANNAME, value, 0);
    }

    public String getSTATE()
    {
        return getStringProperty(ATTR_STATE);
    }

    public void setSTATE(String value)
    {
        setProperty(ATTR_STATE, value, 0);
    }

    public String getTYPE1()
    {
        return getStringProperty(ATTR_TYPE1);
    }

    public void setTYPE1(String value)
    {
        setProperty(ATTR_TYPE1, value, 0);
    }

    public String getTYPE2()
    {
        return getStringProperty(ATTR_TYPE2);
    }

    public void setTYPE2(String value)
    {
        setProperty(ATTR_TYPE2, value, 0);
    }

    public String getTYPE3()
    {
        return getStringProperty(ATTR_TYPE3);
    }

    public void setTYPE3(String value)
    {
        setProperty(ATTR_TYPE3, value, 0);
    }

    public String getTYPE4()
    {
        return getStringProperty(ATTR_TYPE4);
    }

    public void setTYPE4(String value)
    {
        setProperty(ATTR_TYPE4, value, 0);
    }

    public String getTYPE5()
    {
        return getStringProperty(ATTR_TYPE5);
    }

    public void setTYPE5(String value)
    {
        setProperty(ATTR_TYPE5, value, 0);
    }

    public String getPLANID()
    {
        return getStringProperty(ATTR_PLANID);
    }

    public void setPLANID(String value)
    {
        setProperty(ATTR_PLANID, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public java.util.Date getCreatedDate()
    {
        return getDateTimestampProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.util.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getUpdatedDate()
    {
        return getDateTimestampProperty(ATTR_UpdatedDate);
    }

    public void setUpdatedDate(java.util.Date value)
    {
        setProperty(ATTR_UpdatedDate, value, 0);
    }

    public String getCaseType()
    {
        return getStringProperty(ATTR_CaseType);
    }

    public void setCaseType(String value)
    {
        setProperty(ATTR_CaseType, value, 0);
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSOPsCaseHandlingConfig> getWKSOPsCaseHandlingConfigObjects(com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WKSOPsCaseHandlingConfig\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(WKSOPsCaseHandlingConfig.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSOPsCaseHandlingConfig> getWKSOPsCaseHandlingConfigObjects()
    {
        String queryText = "select * from \"WKSOPsCaseHandlingConfig\"";
        QueryObject query = new QueryObject(queryText);
        query.setResultClass(WKSOPsCaseHandlingConfig.class);
        return query.getObjects();
    }


}
