/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import java.util.*;
import com.cordys.cpc.bsf.busobject.BSF;

public class WKSUWDECISIONDETAILS extends WKSUWDECISIONDETAILSBase
{
    public WKSUWDECISIONDETAILS()
    {
        this((BusObjectConfig)null);
    }

    public WKSUWDECISIONDETAILS(BusObjectConfig config)
    {
        super(config);
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> GetWksuwdecisiondetailsByTaskID(String TaskID)
    {
       String queryText = "select * from \"WKSUWDECISIONDETAILS\" where \"TaskIdentifier\" =:TaskID";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("TaskID", "WKSUWDECISIONDETAILS.TaskIdentifier", QueryObject.PARAM_STRING,TaskID );
       
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        
        return query.getObjects();
    }
protected void onBeforeInsert()
{
String userDN = BSF.getUser();
this.setCreatedDate(new Date(new Date().getTime() - (new Date().getTimezoneOffset() * 60 * 1000)));
this.setCreatedBy(userDN.substring(3,userDN.indexOf(",")));
}
protected void onBeforeUpdate()
{
String userDN = BSF.getUser();
this.setUpdatedOn(new Date(new Date().getTime() - (new Date().getTimezoneOffset() * 60 * 1000)));
this.setUpdatedBy(userDN.substring(3,userDN.indexOf(",")));
}
public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> GetWksuwdecisiondetailsByPolicyNumber(String PolicyNumber)
    {
       String queryText = "select * from \"WKSUWDECISIONDETAILS\" where \"ApplicationNumber\" =:PolicyNumber";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("PolicyNumber", "WKSUWDECISIONDETAILS.ApplicationNumber", QueryObject.PARAM_STRING,PolicyNumber);
       
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        
        return query.getObjects();
    }
}
