/*
  This class has been generated by the Code Generator
*/

package com.worksitewsapppackage;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.busobject.QueryObject;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class WKSUWDECISIONDETAILSBase extends com.cordys.cpc.bsf.busobject.StateBusObject
{
    // tags used in the XML document
    public final static String ATTR_SLNO = "SLNO";
    public final static String ATTR_TaskIdentifier = "TaskIdentifier";
    public final static String ATTR_CaseId = "CaseId";
    public final static String ATTR_TaskName = "TaskName";
    public final static String ATTR_ApplicationNumber = "ApplicationNumber";
    public final static String ATTR_CompanyCode = "CompanyCode";
    public final static String ATTR_GroupNumber = "GroupNumber";
    public final static String ATTR_Decision = "Decision";
    public final static String ATTR_CancellationCode = "CancellationCode";
    public final static String ATTR_CancellationReason = "CancellationReason";
    public final static String ATTR_LetterModel = "LetterModel";
    public final static String ATTR_CreatedDate = "CreatedDate";
    public final static String ATTR_CancelledBY = "CancelledBY";
    public final static String ATTR_REALDecisionResponse = "REALDecisionResponse";
    public final static String ATTR_LSPLetterResponse = "LSPLetterResponse";
    public final static String ATTR_ReqNotes = "ReqNotes";
    public final static String ATTR_CreatedBy = "CreatedBy";
    public final static String ATTR_CreatedOn = "CreatedOn";
    public final static String ATTR_UpdatedBy = "UpdatedBy";
    public final static String ATTR_UpdatedOn = "UpdatedOn";
    public final static String ATTR_LetterType = "LetterType";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(WKSUWDECISIONDETAILS.class);
            s_classInfo.setTableName("WKSUWDECISIONDETAILS");
            s_classInfo.setUIDElements(new String[]{ATTR_SLNO});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SLNO);
                ai.setJavaName(ATTR_SLNO);
                ai.setColumnName(ATTR_SLNO);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SLNO);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskIdentifier);
                ai.setJavaName(ATTR_TaskIdentifier);
                ai.setColumnName(ATTR_TaskIdentifier);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskIdentifier);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CaseId);
                ai.setJavaName(ATTR_CaseId);
                ai.setColumnName(ATTR_CaseId);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CaseId);
                v.setMaxLength(100);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskName);
                ai.setJavaName(ATTR_TaskName);
                ai.setColumnName(ATTR_TaskName);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_TaskName);
                v.setMaxLength(10);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ApplicationNumber);
                ai.setJavaName(ATTR_ApplicationNumber);
                ai.setColumnName(ATTR_ApplicationNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ApplicationNumber);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CompanyCode);
                ai.setJavaName(ATTR_CompanyCode);
                ai.setColumnName(ATTR_CompanyCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CompanyCode);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_GroupNumber);
                ai.setJavaName(ATTR_GroupNumber);
                ai.setColumnName(ATTR_GroupNumber);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_GroupNumber);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Decision);
                ai.setJavaName(ATTR_Decision);
                ai.setColumnName(ATTR_Decision);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Decision);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationCode);
                ai.setJavaName(ATTR_CancellationCode);
                ai.setColumnName(ATTR_CancellationCode);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationCode);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancellationReason);
                ai.setJavaName(ATTR_CancellationReason);
                ai.setColumnName(ATTR_CancellationReason);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancellationReason);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LetterModel);
                ai.setJavaName(ATTR_LetterModel);
                ai.setColumnName(ATTR_LetterModel);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LetterModel);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedDate);
                ai.setJavaName(ATTR_CreatedDate);
                ai.setColumnName(ATTR_CreatedDate);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CancelledBY);
                ai.setJavaName(ATTR_CancelledBY);
                ai.setColumnName(ATTR_CancelledBY);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CancelledBY);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_REALDecisionResponse);
                ai.setJavaName(ATTR_REALDecisionResponse);
                ai.setColumnName(ATTR_REALDecisionResponse);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_REALDecisionResponse);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LSPLetterResponse);
                ai.setJavaName(ATTR_LSPLetterResponse);
                ai.setColumnName(ATTR_LSPLetterResponse);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LSPLetterResponse);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ReqNotes);
                ai.setJavaName(ATTR_ReqNotes);
                ai.setColumnName(ATTR_ReqNotes);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_ReqNotes);
                v.setMaxLength(500);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedBy);
                ai.setJavaName(ATTR_CreatedBy);
                ai.setColumnName(ATTR_CreatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_CreatedBy);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CreatedOn);
                ai.setJavaName(ATTR_CreatedOn);
                ai.setColumnName(ATTR_CreatedOn);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedBy);
                ai.setJavaName(ATTR_UpdatedBy);
                ai.setColumnName(ATTR_UpdatedBy);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_UpdatedBy);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UpdatedOn);
                ai.setJavaName(ATTR_UpdatedOn);
                ai.setColumnName(ATTR_UpdatedOn);
                ai.setAttributeClass(java.util.Date.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LetterType);
                ai.setJavaName(ATTR_LetterType);
                ai.setColumnName(ATTR_LetterType);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_LetterType);
                v.setMaxLength(50);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public WKSUWDECISIONDETAILSBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSLNO()
    {
        return getIntProperty(ATTR_SLNO);
    }

    public void setSLNO(int value)
    {
        setProperty(ATTR_SLNO, value, 0);
    }

    public String getTaskIdentifier()
    {
        return getStringProperty(ATTR_TaskIdentifier);
    }

    public void setTaskIdentifier(String value)
    {
        setProperty(ATTR_TaskIdentifier, value, 0);
    }

    public String getCaseId()
    {
        return getStringProperty(ATTR_CaseId);
    }

    public void setCaseId(String value)
    {
        setProperty(ATTR_CaseId, value, 0);
    }

    public String getTaskName()
    {
        return getStringProperty(ATTR_TaskName);
    }

    public void setTaskName(String value)
    {
        setProperty(ATTR_TaskName, value, 0);
    }

    public String getApplicationNumber()
    {
        return getStringProperty(ATTR_ApplicationNumber);
    }

    public void setApplicationNumber(String value)
    {
        setProperty(ATTR_ApplicationNumber, value, 0);
    }

    public String getCompanyCode()
    {
        return getStringProperty(ATTR_CompanyCode);
    }

    public void setCompanyCode(String value)
    {
        setProperty(ATTR_CompanyCode, value, 0);
    }

    public String getGroupNumber()
    {
        return getStringProperty(ATTR_GroupNumber);
    }

    public void setGroupNumber(String value)
    {
        setProperty(ATTR_GroupNumber, value, 0);
    }

    public String getDecision()
    {
        return getStringProperty(ATTR_Decision);
    }

    public void setDecision(String value)
    {
        setProperty(ATTR_Decision, value, 0);
    }

    public String getCancellationCode()
    {
        return getStringProperty(ATTR_CancellationCode);
    }

    public void setCancellationCode(String value)
    {
        setProperty(ATTR_CancellationCode, value, 0);
    }

    public String getCancellationReason()
    {
        return getStringProperty(ATTR_CancellationReason);
    }

    public void setCancellationReason(String value)
    {
        setProperty(ATTR_CancellationReason, value, 0);
    }

    public String getLetterModel()
    {
        return getStringProperty(ATTR_LetterModel);
    }

    public void setLetterModel(String value)
    {
        setProperty(ATTR_LetterModel, value, 0);
    }

    public java.util.Date getCreatedDate()
    {
        return getDateTimestampProperty(ATTR_CreatedDate);
    }

    public void setCreatedDate(java.util.Date value)
    {
        setProperty(ATTR_CreatedDate, value, 0);
    }

    public String getCancelledBY()
    {
        return getStringProperty(ATTR_CancelledBY);
    }

    public void setCancelledBY(String value)
    {
        setProperty(ATTR_CancelledBY, value, 0);
    }

    public String getREALDecisionResponse()
    {
        return getStringProperty(ATTR_REALDecisionResponse);
    }

    public void setREALDecisionResponse(String value)
    {
        setProperty(ATTR_REALDecisionResponse, value, 0);
    }

    public String getLSPLetterResponse()
    {
        return getStringProperty(ATTR_LSPLetterResponse);
    }

    public void setLSPLetterResponse(String value)
    {
        setProperty(ATTR_LSPLetterResponse, value, 0);
    }

    public String getReqNotes()
    {
        return getStringProperty(ATTR_ReqNotes);
    }

    public void setReqNotes(String value)
    {
        setProperty(ATTR_ReqNotes, value, 0);
    }

    public String getCreatedBy()
    {
        return getStringProperty(ATTR_CreatedBy);
    }

    public void setCreatedBy(String value)
    {
        setProperty(ATTR_CreatedBy, value, 0);
    }

    public java.util.Date getCreatedOn()
    {
        return getDateTimestampProperty(ATTR_CreatedOn);
    }

    public void setCreatedOn(java.util.Date value)
    {
        setProperty(ATTR_CreatedOn, value, 0);
    }

    public String getUpdatedBy()
    {
        return getStringProperty(ATTR_UpdatedBy);
    }

    public void setUpdatedBy(String value)
    {
        setProperty(ATTR_UpdatedBy, value, 0);
    }

    public java.util.Date getUpdatedOn()
    {
        return getDateTimestampProperty(ATTR_UpdatedOn);
    }

    public void setUpdatedOn(java.util.Date value)
    {
        setProperty(ATTR_UpdatedOn, value, 0);
    }

    public String getLetterType()
    {
        return getStringProperty(ATTR_LetterType);
    }

    public void setLetterType(String value)
    {
        setProperty(ATTR_LetterType, value, 0);
    }



    public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> getNextWksuwdecisiondetailsObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WKSUWDECISIONDETAILS\" where (\"SLNO\" > :SLNO) order by \"SLNO\" asc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> getPreviousWksuwdecisiondetailsObjects(int SLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WKSUWDECISIONDETAILS\" where (\"SLNO\" < :SLNO) order by \"SLNO\" desc";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static com.worksitewsapppackage.WKSUWDECISIONDETAILS getWksuwdecisiondetailsObject(int SLNO)
    {
        String queryText = "select * from \"WKSUWDECISIONDETAILS\" where \"SLNO\" = :SLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("SLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(SLNO));//NOPMD
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        return (WKSUWDECISIONDETAILS)query.getObject();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> getWksuwdecisiondetailsObjects(int fromSLNO, int toSLNO, com.cordys.cpc.bsf.query.Cursor cursor)
    {
        String queryText = "select * from \"WKSUWDECISIONDETAILS\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        query.setCursor(cursor);
        return query.getObjects();
    }

    public static BusObjectIterator<com.worksitewsapppackage.WKSUWDECISIONDETAILS> getWksuwdecisiondetailsObjects(int fromSLNO, int toSLNO)
    {
        String queryText = "select * from \"WKSUWDECISIONDETAILS\" where \"SLNO\" between :fromSLNO and :toSLNO";
        QueryObject query = new QueryObject(queryText);
        query.addParameter("fromSLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(fromSLNO));
        query.addParameter("toSLNO", "WKSUWDECISIONDETAILS.SLNO", QueryObject.PARAM_INT, new Integer(toSLNO));
        query.setResultClass(WKSUWDECISIONDETAILS.class);
        return query.getObjects();
    }

}
